<?php foreach ($this->rubriques as $rubrique) : ?>
    <div id='afficher_rubrique-<?= $rubrique['ID_RUBRIQUE'] ?>' class="panel panel-formulaire-perso folded<?= boolval($rubrique['DISPLAY']) === false ? ' hide' : '' ?>">
        <div class="panel-heading">
            <h4 id='<?= strtolower(preg_replace('/\s|\'+/', '-', $rubrique['NOM'])) ?>'>
                <?= $rubrique['NOM'] ?>
            </h4>

            <i class="icon icon-chevron-down"></i>
        </div>

        <!-- Style inline pour conserver la règle display: flex; ajoutée en CSS pour le fonctionnement de la méthode show() de jQuery -->
        <div class="panel-body" style="display: none;">
            <?php if (empty($rubrique['CHAMPS'])): ?>
                <?=
                    $this->partial('formulaire/partials/partial-information-manquante.phtml', [
                        'message' => 'Aucun champ renseigné. Contactez un administrateur Prevarisc.'
                    ]);
                ?>
            <?php else : ?>
                <?php foreach ($rubrique['CHAMPS'] as $champ) : ?>
                    <div class='control-group'>
                        <label for='champ-<?= htmlspecialchars($champ["ID_CHAMP"]) ?>' class='control-label'>
                            <strong><?= htmlspecialchars($champ['NOM']) ?></strong>
                        </label>
                        <div class="controls <?php if ($champ['ID_TYPECHAMP'] === 6): ?>table-wrapper<?php endif ?>">
                            <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                                'champ' => $champ,
                                'champsvaleurliste' => $this->champsvaleurliste,
                                'canWrite' => isset($this->canWrite) ? $this->canWrite : false
                            ]); ?>
                        </div>
                    </div>
                <?php endforeach ?>
            <?php endif ?>
        </div>
    </div>
<?php endforeach ?>

<script type="text/javascript">
    $('.panel-heading .icon').click(function () {
        const $self = $(this);
        const $panel = $self.parents('.panel');
        $panel.toggleClass('folded');

        if ($self.hasClass('icon-chevron-up')) {
            $self.removeClass('icon-chevron-up').addClass('icon-chevron-down');
            $panel.find('.panel-body').hide(400);
        } else {
            $self.removeClass('icon-chevron-down').addClass('icon-chevron-up');
            $panel.find('.panel-body').show(400);
        }
    })
</script>
