<div class='span3 control-group'>
    <label for="afficher_rubrique-<?= $this->ID_RUBRIQUE ?>" class='control-label'><?= $this->NOM ?></label>
    <div class='controls'>
        <input
            type="hidden"
            name="afficher_rubrique-<?= $this->ID_RUBRIQUE ?>"
            value="0"
        >
        <input
            type="checkbox"
            name="afficher_rubrique-<?= $this->ID_RUBRIQUE ?>"
            value="1"
            <?= $this->DISPLAY === true ? 'checked' : '' ?>
        >
    </div>
</div>