<?php switch ($this->champ['ID_TYPECHAMP']) {
    // Texte
    case 1: ?>
        <input
            type='text'
            name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"])?>'
            value='<?= isset($this->valeurformulaire[intval($this->champ["ID_CHAMP"])]) ? htmlspecialchars($this->valeurformulaire[$this->champ["ID_CHAMP"]]['VALEUR_STR'], ENT_QUOTES) :'' ?>'
            <?= $this->canWrite ? '': 'disabled'?>
        >
<!--        name= '<?= isset($this->idxTableau) ? 'valeur-'.$this->valeurformulaire[$this->champ["ID_CHAMP"]]['ID_VALEUR'] : 'champ-'.htmlspecialchars($this->champ["ID_CHAMP"]) ?>''
    -->
    <!--
    -->

    <?php break;
    // Texte long
    case 2: ?>
        <textarea name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"])  ?>'<?= $this->canWrite ? '': 'disabled'?>><?= isset($this->valeurformulaire[$this->champ["ID_CHAMP"]]) ? htmlspecialchars($this->valeurformulaire[$this->champ["ID_CHAMP"]]["VALEUR_LONG_STR"], ENT_QUOTES) :'' ?></textarea>
    <?php break;
    // Liste
    case 3: ?>
        <select name='champ-<?= $this->champ["ID_CHAMP"] ?>'<?= $this->canWrite ? '': 'disabled'?>>
            <option selected value>Sélectionnez un élément</option>
            <?php if (!empty($this->champ['VALEUR']))  :?>
                <?php foreach($this->champ['VALEUR'] as $valeurListe): ?>
                    <option
                        value="<?= htmlspecialchars($valeurListe['VALEUR'], ENT_QUOTES) ?>"
                        <?php if (!empty( $this->valeurformulaire[$this->champ["ID_CHAMP"]]['VALEUR_STR'])) :?>
                            <?= $valeurListe['VALEUR'] === $this->valeurformulaire[$this->champ["ID_CHAMP"]]['VALEUR_STR'] ? 'selected' : '' ?>
                        <?php endif?>
                    >
                        <?= htmlspecialchars($valeurListe['VALEUR']) ?>
                    </option>
                <?php endforeach ?>
            <?php else:?>
                <option>
                    <?= "Aucune valeur de disponible" ?>
                </option>
            <?php endif ?>
        </select>
    <?php break;
    // Nombre
    case 4: ?>
        <input type='number' name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"]) ?>'<?= $this->canWrite ? '': 'disabled'?> min='0' value='<?= $this->valeurformulaire[$this->champ["ID_CHAMP"]]['VALEUR_INT'] ?>'>
    <?php break;
    // Case à cocher
    case 5: ?>
        <input
            type="hidden"
            name='champ-<?= htmlspecialchars($this->champ['ID_CHAMP']) ?>'
            value="0"
            <?= $this->canWrite ? '': 'disabled'?>
        >
        <input
            type="checkbox"
            name='champ-<?= htmlspecialchars($this->champ['ID_CHAMP']) ?>'
            value="1"
            <?= $this->canWrite ? '': 'disabled'?>
            <?= !empty($this->valeurformulaire[ $this->champ['ID_CHAMP']]['VALEUR_CHECKBOX']) ? 'checked' : '' ?>
        >
    <?php break;   

    case 6:?>
    <?php if(intval(empty($this->champ['tableau']) ? 0 : $this->champ['tableau']) === 1) : ?>
        <?php if(isset($this->canWrite) ? $this->canWrite : false) :?>
            <!-- [button type='button'] pour desactiver le submit auto suite a un clic de bouton -->
            <button type='button' class='btn addRow' attr=<?= $this->champ['ID_CHAMP']?>>Ajouter ligne</button>
        <?php endif ?>
        <table class='table table-striped '>
            <thead>
                <tr>
                <?php if(isset($this->canWrite) ? $this->canWrite : true) :?>
                        <th>#</th>
                <?php endif ?>
                    <th>IDX</th>
                    <?php foreach($this->champ['CHAMP_FILS'] as $champsFils) :?>
                        <th><?= $champsFils['NOM'] ?></th>
                    <?php endforeach ?>
                    <?php if(isset($this->canWrite) ? $this->canWrite : true) :?>
                        <th>Supprimer</th>
                    <?php endif ?>
                </tr>
            </thead>
            <tbody id= <?= 'tbody-'.$this->champ['ID_CHAMP'] ?> class='grp'>
            <tr id='ligneTableau' class='hidden'>
                <?php if(isset($this->canWrite) ? $this->canWrite : true) :?>
                    <td class='tdMove'>
                        <i class="icon-move"></i>
                    </td>
                <?php endif ?>
                <td></td>
                <?php foreach($this->champ['CHAMP_FILS'] as $champsFils) :?>
                        <td>
                            <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                                'champ' => $champsFils,
                                'canWrite' => isset($this->canWrite) ? $this->canWrite : false
                                ]); 
                            ?>
                        </td>
                <?php endforeach ?>
                <td>
                    <?php if(isset($this->canWrite) ? $this->canWrite : false) :?>
                        <button type='button' class='deleteRow btn btn-danger'><i class='icon-trash'></i></button>
                    <?php endif?>
                </td>
            </tr>
                <?php foreach($this->valeurformulaire['RES_TABLEAU'] as $k => $ligneValeur): ?>
                <tr id=<?= 'tr-'.$k ?>>
                    <?php if(isset($this->canWrite) ? $this->canWrite : true) :?>
                            <td class='tdMove'>
                                <i class="icon-move"></i>
                            </td>
                    <?php endif ?>
                    <td>
                        <?= $k ?>
                    </td>
                    <!--Construction de la ligne avec les champs-->
                    <?php foreach($ligneValeur as $idParent => $listValeur): ?>
                        <?php if($idParent === $this->champ['ID_CHAMP']) : ?>
                            <?php foreach($this->champ['CHAMP_FILS'] as $champsFils) :?>
                                <td>
                                    <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                                        'champ' => $champsFils,
                                        'valeurformulaire' => $listValeur,
                                        'canWrite' => isset($this->canWrite) ? $this->canWrite : false,
                                        'idxTableau' => $k
                                        ]); 
                                    ?>
                                </td>
                            <?php endforeach ?>      
                        <?php endif ?>
                    <?php endforeach ?>    
                    
                    <?php if(isset($this->canWrite) ? $this->canWrite : true) :?>
                        <td>
                            <!-- [button type='button'] pour desactiver le submit auto suite a un clic de bouton -->
                                <button type='button' class='deleteRow btn btn-danger'><i class='icon-trash'></i></button>
                        </td>
                    <?php endif?>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php else : ?>
        <div class="tableInput">
            <?php foreach ($this->champ["CHAMP_FILS"] as $champsFils): ?>
                <div class="colTableInput">
                    <th><?= $champsFils['NOM'] ?></th>
                    <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                        'champ' => $champsFils,
                        'valeurformulaire' => $this->valeurformulaire,
                        'canWrite' => isset($this->canWrite) ? $this->canWrite : false
                        ]); 
                    ?>
                </div>
            <?php endforeach;?>
        </div>
    <?php endif?>
    <?php break;
    default:
        break;
} ?>

<script>
    window.onload = () => {
        $('.addRow').click(function() {
            $('#tbody-'+$(this).attr('attr')).append('<tr>'+$('#ligneTableau').html()+'</tr>')
            $('.deleteRow').click(function(){
                $(this).closest('tr').remove();
            })
        })

        $('.deleteRow').click(function(){
            $(this).closest('tr').remove();
        })
    }
</script>
