<?php foreach ($this->rubriques as $rubrique) : ?>
    <div
        id='afficher_rubrique-<?= $rubrique['ID_RUBRIQUE'] ?>'
        class="panel panel-formulaire-perso <?php if (boolval($rubrique['ouverte']) === false): ?>folded<?php endif ?> <?php if (boolval($rubrique['DISPLAY']) === false): ?>hide<?php endif ?>"
    >
        <div class="panel-heading">
            <h4 id='<?= strtolower(preg_replace('/\s|\'+/', '-', $rubrique['NOM'])) ?>'>
                <?= $rubrique['NOM'] ?>
            </h4>

            <i class="icon <?php if (boolval($rubrique['ouverte']) === false): ?>icon-chevron-down<?php else: ?>icon-chevron-up<?php endif ?>"></i>
        </div>

        <div class="panel-body <?php if (boolval($rubrique['ouverte']) === false): ?>panel-body-hidden<?php endif ?>">
            <?php if (empty($rubrique['CHAMPS'])): ?>
                <?=
                    $this->partial('formulaire/partials/partial-information-manquante.phtml', [
                        'message' => 'Aucun champ renseigné. Contactez un administrateur Prevarisc.'
                    ]);
                ?>
            <?php else : ?>
                <?php foreach ($rubrique['CHAMPS'] as $champ) : ?>
                    <div class='control-group'>
                        <label for='champ-<?= htmlspecialchars($champ["ID_CHAMP"]) ?>' class='control-label'>
                            <strong><?= htmlspecialchars($champ['NOM']) ?></strong>
                        </label>
                        <div class="controls <?php if ($champ['ID_TYPECHAMP'] === 6): ?>table-wrapper<?php endif ?>">
                            <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                                'champ' => $champ,
                                'champsvaleurliste' => $this->champsvaleurliste,
                                'canWrite' => isset($this->canWrite) ? $this->canWrite : false
                            ]); ?>
                        </div>
                    </div>
                <?php endforeach ?>
            <?php endif ?>
        </div>
    </div>
<?php endforeach ?>

<script type="text/javascript">
    $('.panel-heading .icon').click(function () {
        const $self = $(this);
        const $panel = $self.parents('.panel');
        const $body = $panel.find('.panel-body');

        $self.toggleClass('icon-chevron-down');
        $self.toggleClass('icon-chevron-up');
        $panel.toggleClass('folded');
        $body.toggleClass('panel-body-hidden');
    })
</script>
