<?php switch ($this->champ['ID_TYPECHAMP']) {
    case 1:
    case 3:
    case 4: ?>
        <span><?= htmlspecialchars($this->champ['VALEUR'], ENT_QUOTES) ?></span>

        <?php break;
    case 2: ?>
        <span><?= nl2br(htmlspecialchars($this->champ['VALEUR'], ENT_QUOTES)) ?></span>

        <?php break;
    case 7: ?>
        <span><?= htmlspecialchars(Service_Utils_Date::formatDateWithDayName($this->champ['VALEUR']), ENT_QUOTES) ?></span>

        <?php break;
    default:
        break;
} ?>
