<?php switch ($this->champ['ID_TYPECHAMP']) {
    case 1:
    case 3:
    case 4:
        echo htmlspecialchars($this->champ['VALEUR'], ENT_QUOTES);

        break;
    case 2:
        echo nl2br(htmlspecialchars($this->champ['VALEUR'], ENT_QUOTES));

        break;
    case 7:
        echo htmlspecialchars(Service_Utils_Date::formatDateWithDayName($this->champ['VALEUR']), ENT_QUOTES);

        break;
    default:
        break;
} ?>
