<?php switch ($this->champ['ID_TYPECHAMP']) {
    // Texte
    case 1: ?>
        <input
            type='text'
            name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"]) ?>'
            value='<?= htmlspecialchars($this->champ['VALEUR'], ENT_QUOTES) ?>'
            <?= $this->canWrite ? '': 'disabled'?>
        >
    <?php break;
    // Texte long
    case 2: ?>
        <textarea name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"])  ?>'<?= $this->canWrite ? '': 'disabled'?>><?= htmlspecialchars($this->champ['VALEUR'], ENT_QUOTES) ?></textarea>
    <?php break;
    // Liste
    case 3: ?>
        <select name='champ-<?= $this->champ["ID_CHAMP"] ?>'<?= $this->canWrite ? '': 'disabled'?>>
            <option selected value>Sélectionnez un élément</option>
            <?php foreach($this->champsvaleurliste[$this->champ['ID_CHAMP']] as $champvaleurliste): ?>
                <option
                    value="<?= htmlspecialchars($champvaleurliste['VALEUR'], ENT_QUOTES) ?>"
                    <?= $champvaleurliste['VALEUR'] === $this->champ['VALEUR'] ? 'selected' : '' ?>
                >
                    <?= $champvaleurliste['VALEUR'] ?>
                </option>
            <?php endforeach ?>
        </select>
    <?php break;
    // Nombre
    case 4: ?>
        <input type='number' name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"]) ?>'<?= $this->canWrite ? '': 'disabled'?> min='0' value='<?= $this->champ['VALEUR'] ?>'>
    <?php break;
    // Case à cocher
    case 5: ?>
        <input
            type="hidden"
            name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"]) ?>'
            value="0"
            <?= $this->canWrite ? '': 'disabled'?>
        >
        <input
            type="checkbox"
            name='champ-<?= htmlspecialchars($this->champ["ID_CHAMP"]) ?>'
            value="1"
            <?= $this->canWrite ? '': 'disabled'?>
            <?= $this->champ['VALEUR'] ? 'checked' : '' ?>
        >
    <?php break;
    // Parent
    case 6:?>
        <div class="tableInput">
            <?php foreach ($this->champ["FILS"] as $champsFils): ?>
                <div class="colTableInput">
                    <th><?= $champsFils['NOM'] ?></th>
                    <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                            'champ' => $champsFils,
                            'champsvaleurliste' => $this->champsvaleurliste,
                            'canWrite' => isset($this->canWrite) ? $this->canWrite : false
                        ]);
                    ?>
                </div>
            <?php endforeach;?>
        </div>
    <?php break;
    default:
        break;
} ?>
