<div id="saved-champs-prototype" class="hidden col-md-6 col-md-offset-2 saved-fields">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"></h3>
        </div>
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th></th>
                    <th>Nom du champ</th>
                    <th>Type du champ</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
