<!-- Titre -->
<h3 class='page-header'>Tableau des périodicités <small>(Les valeurs sont affichées et à saisir en mois)</small></h3>

<form id='form_periodicite' action='/tableau-des-periodicites/save' method='post' >
	<h3>ERP</h3>
        <!-- Types pour lesquels on ne définit pas la périodicité sans hebergement -->
        <?php
        if (getenv('PREVARISC_LOCAL_SOMMEIL_TYPES') != false){
            $localsommeil_types = explode(';',getenv('PREVARISC_LOCAL_SOMMEIL_TYPES'));
        } else $localsommeil_types = array(7,11);
        ?>

	<!-- Tableaux -->

	<?php foreach( array_chunk($this->array_types, 7) as $array_types ) : ?>
	<table class='table table-bordered table-condensed periodicite' >
		<thead>
			<tr>
				<th rowspan="2"></th>
				<?php foreach( $array_types as $type) : ?>
					<th colspan='2' ><?php echo $type["LIBELLE_TYPE"] ?></th>
				<?php endforeach ?>
			</tr>
			<tr>
				<?php for($i = 0; $i < count($array_types); $i++) : ?>
					<th style='height: 26px; background: url(/css/images/avec_sans_local.gif) center -13px no-repeat' ></th>
					<th style='height: 26px; background: url(/css/images/avec_sans_local.gif) center 6px no-repeat' ></th>
				<?php endfor ?>
			</tr>
		</thead>
		<tbody>
			<?php foreach( $this->array_categories as $categorie) : ?>
			<tr>
				<td style='width: 150px;' ><?php echo $categorie["LIBELLE_CATEGORIE"] ?></td>

				<?php foreach( $array_types as $type) : ?>
					<?php $periodicite = $this->tableau[$categorie["ID_CATEGORIE"]][$type["ID_TYPE"]]; ?>

					<td style='text-align: center' >
						<?php if(!in_array($type["ID_TYPE"], $localsommeil_types)) : ?>
							<input class="form-control" type='text' size='3' maxlength='3' value='<?= $periodicite[0] ?: 0 ?>' name='<?php echo $categorie["ID_CATEGORIE"]."_".$type["ID_TYPE"]."_0" ?>' />
						<?php else : ?>
							<input type='text' size='3' style='visibility: hidden' />
						<?php endif ?>
					</td>

					<td style='text-align: center' >
                        <input class="form-control" type='text' size='3' maxlength='3' value='<?= $periodicite[1] ?: 0 ?>' name='<?php echo $categorie["ID_CATEGORIE"]."_".$type["ID_TYPE"]."_1" ?>' />
					</td>
				<?php endforeach ?>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
	<?php endforeach ?>

	<h3>IGH</h3>
	<table class='table table-bordered table-condensed periodicite' >
		<thead>
			<tr>
				<?php foreach($this->array_classes as $classe) : ?>
					<th ><?php echo $classe["LIBELLE_CLASSE"] ?></th>
				<?php endforeach ?>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php foreach( $this->array_classes as $classe) : ?>
					<?php $periodicite = $this->tableau[0][$classe["ID_CLASSE"]]; ?>

					<td style='text-align: center' >
						<input class="form-control" type='text' size='3' maxlength='3' value='<?= $periodicite[0] ?: 0 ?>' name='<?php echo "0_".$classe["ID_CLASSE"]."_0" ?>' />
					</td>
				<?php endforeach ?>
			</tr>
		</tbody>
	</table>


    <p class='text-center'>
		<input type='submit' id='submit' value='Sauvegarder' class='btn btn-success' />
        <a href="/tableau-des-periodicites/apply" onClick="return confirm('Etes-vous sûr de vouloir appliquer ces paramètres à l\'ensemble des établissements ?');"class='btn btn-primary'>Appliquer sur TOUS les établissements</a>
    </p>

</form>

<script type="text/javascript">
	$("input[type=text]").change(function() {
		if($(this).val() == "0") {
			$(this).css("opacity", .5);
		}else {
			$(this).css("opacity", 1);
		}
	}).change();
</script>
