<td class='tdMove'>
    <i class="icon-move"></i>
</td>
<?php $genTimesTamp = time(); ?>
<?php foreach($this->inputs as &$input) : ?>

    <?php
        $input['STR_DATA'] = 'valeur-'.$genTimesTamp.'-'.$input['ID_PARENT'].'-'.$input['ID_CHAMP'].'-NULL';
    ?>
    <td>
        <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                'champ' => $input,
                'canWrite' => true,
                'idxTableau' => '0',
            ]);
        ?>
    </td>
<?php endforeach ?>
<td>
    <button type='button' class='deleteRow btn btn-danger'><i class='icon-trash'></i></button>
</td>
