<?php foreach($this->colonnesChamp['VALEURS'] as $colonneChamp) : ?>
    <tr class='<?= $this->hidden ?'hidden' : '' ?>' >
        <?php if(isset($this->canWrite) ? $this->canWrite : true) :?>
            <td class='tdMove'>
                <i class="icon-move"></i>
            </td>
        <?php endif ?>
        <?php foreach($colonneChamp as $valeur):?>
            <td>
                <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                        'champ' => $valeur,
                        'canWrite' => isset($this->canWrite) ? $this->canWrite : false,
                        'idxTableau' => $valeur['IDX_VALEUR'],
                        'idParent' => $valeur['ID_PARENT']
                    ]);
                ?>
            </td>
        <?php endforeach ?>
        <td>
            <?php if(isset($this->canWrite) ? $this->canWrite : false) :?>
                <button type='button' class='deleteRow btn btn-danger'><i class='icon-trash'></i></button>
            <?php endif?>
        </td>
    </tr>
<?php endforeach ?>
