<?php $genTimesTamp = time(); ?>
<?php foreach ($this->inputs as &$input) : ?>
    <?php
        $input['STR_DATA'] = 'valeur-'.$genTimesTamp.'-'.$input['ID_PARENT'].'-'.$input['ID_CHAMP'];
    ?>
    <td>
        <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                'champ' => $input,
                'canWrite' => true,
                'idxTableau' => '0',
                'champsvaleurliste' => $this->champsvaleurliste
            ]);
        ?>
    </td>
<?php endforeach ?>
<td>
    <button type="button" class="tdMove btn btn-info">
        <i class="icon-move icon-white"></i>
    </button>
    <button type='button' class='deleteRow btn btn-danger'>
        <i class='icon-trash icon-white'></i>
    </button>
</td>
