<td class='tdMove'>
    <i class="icon-move"></i>
</td>
<?php foreach($this->patterns as $pattern) : ?>
    <td>
        <?= $this->partial('formulaire/partials/partial-input-champ.phtml', [
                'champ' => $pattern,
                'canWrite' => true
            ]);
        ?>
    </td>
<?php endforeach ?>
<td>
    <button type='button' class='deleteRow btn btn-danger'><i class='icon-trash'></i></button>
</td>
