<form class="modal fade contact" tabindex="-1" role="dialog" action='<?php echo $this->url(array('action' => 'add-contact-existant')) ?>' method='post'>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Ajouter un contact existant</h3>
            </div>

            <div class="modal-body" style='min-height: 100px;overflow-y:visible'>
                <p class='text-center'>
                    <input type='text' name='autocomplete-ignoreit' placeholder='Nom du contact à ajouter ...' />
                </p>

                <p id='bloc-contact-existant' class='text-center lead'>
                    <span class='text-muted'>Aucun contact selectionné</span>
                    <input type='hidden' name='id_contact' />
                </p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                <input type='submit' id='submit' value='Ajouter' class='btn btn-success' />
            </div>
        </div>
    </div>
</form>

<script>
	// Auto-complétion des préventionnistes
    // @fixme: Faire fonctionner
    // $("input[name='autocomplete-ignoreit']").typeahead({
    //     minLength: 3,
    //     source: function(query, process) {
    //         return $.ajax({
    //             url: "/api/1.0/contacts",
    //             type: 'post',
    //             data: {
    //                 name: query
    //             },
    //             success: function (result) {
    //                 contacts = [];
    //                 $.each(result.response, function (i, contact) {
    //                     contacts.push("<span data-id='" + contact.ID_UTILISATEURINFORMATIONS + "'>"
    //                             + contact.SOCIETE_UTILISATEURINFORMATIONS + " "
    //                             + contact.NOM_UTILISATEURINFORMATIONS + " "
    //                             + contact.PRENOM_UTILISATEURINFORMATIONS
    //                             + "</span>");
    //                 });

    //                 process(contacts);
    //             }
    //         });
    //     },
    //     highlighter: function (item) {
    //         libelle = $($.parseHTML(item)).last().text();
    //         libelle = libelle.replace( new RegExp( '(' + this.query + ')', 'gi' ), "<strong>$1</strong>" );
    //         html = $.parseHTML(item);
    //         $(html).last().text(libelle);
    //         html = $(html).text();
    //         return item.replace( item, html );
    //     },
    //     updater: function (item) {
    //         $('#bloc-contact-existant span').removeClass('text-muted').text($($.parseHTML(item)).last().text());
    //         $('#bloc-contact-existant input[type="hidden"]').val($($.parseHTML(item)).last().data('id'));
    //         return;
    //     }
    // });
</script>
