<form action="<?= $this->url(array('controller' => 'etablissement', 'action' => 'effectifs-degagements-etablissement-edit', 'id' => $this->idEtablissement), false, true) ?>" method="post">
    <div class='pull-right'>
        <a href="<?= $this->url(array('controller' => 'etablissement', 'action' => 'effectifs-degagements-etablissement', 'id' => $this->idEtablissement), false, true) ?>" class='btn'>Annuler la modification</a>
        <input type='submit' class="btn btn-success" value="Sauvegarder">
    </div>

    <h3>
        Effectifs
    </h3>
    <textarea name='DESCRIPTION_EFFECTIF'><?php if (isset($this->EffectifDegagement[0]["DESCRIPTION_EFFECTIF"])) { echo $this->EffectifDegagement[0]["DESCRIPTION_EFFECTIF"]; } ?></textarea>

    <h3>
        Dégagements
    </h3>
    <textarea name='DESCRIPTION_DEGAGEMENT'><?php if (isset($this->EffectifDegagement[0]["DESCRIPTION_DEGAGEMENT"])) { echo $this->EffectifDegagement[0]["DESCRIPTION_DEGAGEMENT"]; } ?></textarea>
</form>
