<?php
if (!isset($this->bloc)) {
    return;
}
$bloc = $this->bloc;
$blocId = $this->blocId;
?>

<div id="<?php echo $this->escape($blocId) ?>" class="panel panel-default panel-ouvrable" data-type="<?php echo $this->escape($this->dataType) ?>">
    <div class="panel-heading">
        <?php if (isset($bloc['count']) && (int)$bloc['count'] > 0): ?>
            <div class="compteur">
                <?php echo (int)$bloc['count']; ?>
            </div>
        <?php endif; ?>
        <?php echo $this->escape($bloc['title']) ?>
    </div>

    <div class="panel-footer">
        <button class="btn-ouvrir" type="button">
            <i class="icon icon-folder-open"></i>
            Ouvrir
            <i class="icon icon-chevron-right"></i>
        </button>
    </div>
</div>
