<div id="<?php echo $this->id ?>" class="panel panel-default <?php echo $this->width != 'small' ? 'w2' : '' ?> empty folded">
  <div class="panel-heading">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <?= $this->title.' ('.($this->count ?? 0).')' ?>
  </div>
  <div class="panel-body" style="display:none">
      <img src="/images/load.gif" />
  </div>
</div>
