<div id="<?php echo $this->id ?>" class="panel panel-default w2 empty folded">
  <div class="panel-heading">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    Ordre du jour des prochaines commissions
    <?= $this->title ?> <span class="badge"><?= $this->count ?? 0 ?></span>

  </div>
  <div class="panel-body" style="font-size: .85em;display:none">
      <img src="/images/load.gif" />
  </div>
</div>

