<?php foreach ($this->listePj as $pj) : ?>
<tr class= 'table_liste'>    
    <?php  /* Lien de la pièce jointe */ ?>
    <td>
        <a 
            class="file <?php echo substr(strtolower($pj['EXTENSION_PIECEJOINTE']), 1, 3) ?>"
            href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type)) ?>' <?php if ($pj['DESCRIPTION_PIECEJOINTE']): ?> title="<?php echo $pj['DESCRIPTION_PIECEJOINTE'] ?>" <?php endif ?> target='_blank' ><?php echo $pj['NOM_PIECEJOINTE'].$pj['EXTENSION_PIECEJOINTE'] ?></a>
    </td>
    
    <?php /* Description */ ?>
    <td><?php echo nl2br(str_replace("<br />", "" ,$pj['DESCRIPTION_PIECEJOINTE'])) ?></td>
    
    <?php /* date de création*/ ?>
    <td>
        <?php
            $date = new Zend_Date($pj['DATE_PIECEJOINTE'], Zend_Date::DATES);
            echo $date->get( Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR );
        ?>
    </td>
    <td>
        <?php if(($this->verrou != 1) && ($pj['SIGNE_PIECEJOINTE'] != 1)): ?>
            <a class='sign' href='/dossier/sign?id=<?php echo  $this->id?>&id_pj= <?php echo $pj['ID_PIECEJOINTE']?>&fileName=<?php echo $pj['NOM_PIECEJOINTE']?>&email_address=<?php echo $this->mail_user?>'>
                 <i class="icon-pencil"></i>
            </a>
        <?php endif ?>
    </td>
    <td>
          <i class="<?php echo  $this->translateStatus;?>" title="<?php echo $this->infoStatus;?>"></i>
    </td>
    <?php /* Action*/ ?>
    <td>
    <button class='addPJSigne' value='<?php echo $pj["ID_PIECEJOINTE"] ?>'>
        <i class="icon-plus-sign"></i>
    </button>
    </td>
    <td>
        <?php if($this->verrou != 1): ?>
            <a class='delete' href='/piece-jointe/delete?id_pj=<?php echo $pj["ID_PIECEJOINTE"] ?>&type=<?php echo $this->type ?>&id=<?php echo $this->id ?>'>
                <i class="icon-trash"></i>
            </a>
        <?php endif ?>
    </td>
</tr>  
<?php endforeach ?>



