<?php foreach ($this->listePj as $pj) : ?>
    <tr>
        <!-- Lien de la pièce jointe -->
        <td>
            <a
                class="file <?php echo substr(strtolower($pj['EXTENSION_PIECEJOINTE']), 1, 3) ?>"
                href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type)) ?>'
                <?php if ($pj['DESCRIPTION_PIECEJOINTE']): ?> title="<?php echo $pj['DESCRIPTION_PIECEJOINTE'] ?>" <?php endif ?>
                target='_blank'
            >
                <?php echo $pj['NOM_PIECEJOINTE'].$pj['EXTENSION_PIECEJOINTE'] ?>
            </a>
            <?php if (
                $this->isPlatau
                && $pj['ID_PLATAU']
            ): ?>
                <br />
                <div class="label label-info">
                    <?= $pj['ID_PLATAU'] ?>
                </div>
            <?php endif ?>
        </td>

        <!-- Description -->
        <td><?php echo nl2br(str_replace("<br />", "" ,$pj['DESCRIPTION_PIECEJOINTE'])) ?></td>

        <!-- Date de création -->
        <td>
            <?php
                $date = new Zend_Date($pj['DATE_PIECEJOINTE'], Zend_Date::DATES);
                echo $date->get( Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR );
            ?>
        </td>

        <?php if ($this->isPlatau): ?>
            <td>
                <?php switch ($pj['NOM_STATUT']):
                    case 'not_exported': ?>
                        <div class="label"><?= $pj['NOM_LISIBLE'] ?></div>
                <?php break;
                    case 'to_be_exported': ?>
                        <div class="label label-info"><?= $pj['NOM_LISIBLE'] ?></div>
                <?php break;
                    case 'awaiting_status': ?>
                        <div class="label label-warning"><?= $pj['NOM_LISIBLE'] ?></div>
                <?php break;
                    case 'exported': ?>
                        <div class="label label-success"><?= $pj['NOM_LISIBLE'] ?></div>
                <?php break;
                    case 'on_error': ?>
                        <div class="label label-important"><?= $pj['NOM_LISIBLE'] ?></div>
                        <i
                            class='icon-label-right icon-info-sign'
                            title='Erreur'
                            data-content="<?= $pj['MESSAGE_ERREUR'] ?>"
                            data-html='true'
                            data-placement='left'
                        ></i>
                        <a href="#" class="retry-export-platau" data-id="<?= $pj['ID_PIECEJOINTE'] ?>">Renvoyer</a>
                <?php break;
                    case null:
                    default: ?>
                        <div class="label label-warning">Statut inconnu</div>
                <?php endswitch ?>
            </td>
        <?php endif ?>

        <!-- Action -->
        <td>
            <?php if($this->verrou != 1 && !in_array($pj['NOM_STATUT'], ['to_be_exported', 'exported', 'awaiting_status'])): ?>
                <a class='delete' href='/piece-jointe/delete?id_pj=<?php echo $pj["ID_PIECEJOINTE"] ?>&type=<?php echo $this->type ?>&id=<?php echo $this->id ?>'>
                    <i class="icon-trash"></i>
                </a>
            <?php endif ?>
        </td>
    </tr>
<?php endforeach ?>

<script type="text/javascript">
    $('.icon-label-right').popover()
</script>
