<?php

	echo "
		<div class='row'>
			<div class='col-md-9' >
				<a href='/gestion-prescriptions'>Gestion des prescriptions types</a> <span class='glyphicon glyphicon-chevron-right' aria-hidden='true'></span> Gestion des articles
			</div>
			<div class='col-md-3' style='float:right;'>
				
			</div>
		</div>
		<h3 class='page-header'>
			Gestion des articles
		</h3>
		<div class='row'>
			<div class='col-md-12' style='text-align:right;'>
				<a class='btn btn-default' href='/gestion-prescriptions/gestion-articles-add'><span class='glyphicon glyphicon-plus' aria-hidden='true'></span>&nbsp;Ajouter un article</a>
			</div>
		</div>

		
		<br/>
	";

	foreach($this->liste_articles as $article)
	{
		if($article['ID_ARTICLE'] != 1)
		{
			echo "
				<div class='row' >
					<div class='col-md-2' style='text-align:right;'>
						".( ($article['VISIBLE_ARTICLE'] == 1 )? "<img src='/images/visible.gif' alt='visible' />" : "<img src='/images/nonvisible.gif' alt='non visible' />")."
						<a class='btn' href='/gestion-prescriptions/gestion-articles-edit/id/".$article['ID_ARTICLE']."' ><span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>&nbsp;Modifier</a>
					</div>
					<div class='col-md-10' >".$article['LIBELLE_ARTICLE']."</div>					
				</div>
				<br/>
			";
		}
	}