SET NAMES 'utf8';

CREATE TABLE IF NOT EXISTS `capsulerubrique` (
    `ID_CAPSULERUBRIQUE` bigint(20) NOT NULL AUTO_INCREMENT,
    `NOM_INTERNE` varchar(255) NOT NULL,
    `NOM` varchar(255) NOT NULL,
    PRIMARY KEY (`ID_CAPSULERUBRIQUE`)
);