SET NAMES 'utf8';

ALTER TABLE `avisderogations` DROP COLUMN `INFORMATIONS`;

ALTER TABLE `avisderogations` ADD COLUMN `OBJET` TEXT DEFAULT NULL AFTER `TITRE`;
ALTER TABLE `avisderogations` ADD COLUMN `JUSTIFICATION` TEXT DEFAULT NULL AFTER `OBJET`;
ALTER TABLE `avisderogations` ADD COLUMN `ARTICLES_CONCERNES` TEXT DEFAULT NULL AFTER `JUSTIFICATION`;
ALTER TABLE `avisderogations` ADD COLUMN `MESURES_COMPENSATOIRES_PROPOSEES` TEXT DEFAULT NULL AFTER `ARTICLES_CONCERNES`;
ALTER TABLE `avisderogations` ADD COLUMN `ANALYSE_DE_RISQUE` TEXT DEFAULT NULL AFTER `MESURES_COMPENSATOIRES_PROPOSEES`;