<div class='pull-right' >
    <a class='btn' href="<?= $this->url(array('action' => 'edit-descriptif')) ?>">Modifier les descriptifs</a>
</div>

<div id='descriptif-personnalise'>
    <h3>Descriptifs</h3>

    <h4 class='h4_subtitle'>Descriptif technique</h4>
    <?= $this->partialLoop('formulaire/partials/partial-rubrique-display.phtml', $this->rubriques) ?>

    <div id='affichage-informations' class='form-horizontal'>
        <?= $this->partial('formulaire/partials/partial-form-custom.phtml', [
                    'corpsformulaire' => isset($this->corpsformulaire) ? $this->corpsformulaire : array(),
                    'valeurformulaire' => isset($this->valeurformulaire) ? $this->valeurformulaire : array(),
                    'canWrite' => false
                ]); 
        ?>
    </div>
</div>