<div class='pull-right' >
    <a class='btn' href="<?= $this->url(array('action' => 'edit-descriptif')) ?>">Modifier les descriptifs</a>
</div>

<div id='descriptif-personnalise'>
    <h3>Descriptifs</h3>

    <h4 class='h4_subtitle'>Descriptif technique</h4>
    <?= $this->partialLoop('formulaire/partials/partial-rubrique-display.phtml', $this->rubriques) ?>

    <div id='affichage-informations' class='form-horizontal'>
        <?= $this->partial('formulaire/formLoopInputChamp.phtml', [
                'rubriques' => isset($this->rubriques) ? $this->rubriques : [],
                'champsvaleurliste' => isset($this->champsvaleurliste) ? $this->champsvaleurliste : [] ,
                'listeChampFils' => isset($this->listeChampFils) ? $this->listeChampFils : [] ,
                'canWrite' => false
            ]); 
        ?>
    </div>

</div>