<form action='<?= $this->url(array('action' => 'edit-descriptif')) ?>' method='post'>
    <div class='action-buttons pull-right'>
        <div class="btn-group">
            <a class='btn' href="<?= $this->url(array('action' => 'descriptif')) ?>" data-do-not-unload>Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder' data-do-not-unload>
        </div>
    </div>

    <h3>Modification des descriptifs</h3>
    <div class="form-layout">
        <?= $this->partial('formulaire/_table_of_content.phtml', [
            'rubriques' => $this->rubriques,
        ]) ?>

        <div class="main-content">
            <?= $this->partial('formulaire/partials/partial-form-custom.phtml', [
                'rubriques' => $this->rubriques,
                'champsvaleurliste' => $this->champsvaleurliste,
                'canWrite' => true
            ]); ?>
        </div>
    </div>
</form>
