<form action='<?= $this->url(array('action' => 'edit-descriptif')) ?>' method='post' class='form-horizontal'>
    <div class='pull-right' >
        <div class="btn-group">
            <a class='btn' href="<?= $this->url(array('action' => 'descriptif')) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>

    <h3>Modification des descriptifs</h3>
    <h4 class='h4_subtitle'>Descriptif</h4>

    <div class='row-fluid'>
        <div class='span10'>
            <?php foreach ($this->rubriques as $key => $rubrique):
                if (($key % 4) === 0): ?>
                    <div class='row-fluid'>
                <?php endif;

                echo $this->partial('formulaire/partials/partial-edit-rubrique-display.phtml', $rubrique);   
                
                if ((($key % 4) === 3) || ($rubrique === end($this->rubriques))): ?>
                    </div>
                <?php endif;
            endforeach ?>
        </div>
    </div>
    <?php foreach ($this->rubriques as $rubrique): ?>
        <div id='afficher_rubrique-<?= $rubrique['ID_RUBRIQUE'] ?>' class="<?= boolval($rubrique['DISPLAY']) === false ? 'hide' : '' ?>">
            <h4 class='h4_subtitle'><?= $rubrique['NOM'] ?></h4>
            <?php if (!empty($rubrique['CHAMPS'])): ?>
                <?php foreach ($rubrique['CHAMPS'] as $champ): ?>
                    <div class='control-group'>
                        <label for='champ-<?= htmlspecialchars($champ["ID_CHAMP"]) ?>' class='control-label'>
                            <strong><?= htmlspecialchars($champ['NOM']) ?></strong>
                        </label>
                        <div class='controls'>
                            <?= $this->partial('formulaire/inputChamp.phtml', [
                                    'champ' => $champ,
                                    'champsvaleurliste' => $this->champsvaleurliste,
                                    'listeChampFils' => $this->listeChampFils,
                                    'isChampFils' => false,
                                    'canWrite' => isset($this->canWrite) ? $this->canWrite : true
                                ]); 
                            ?>
                        </div>
                    </div>
                <?php endforeach ?>
            <?php endif ?>
        </div>
    <?php endforeach ?>

</form>