<form class="modal fade" id="editModal_<?= $formulaire['ID_CAPSULERUBRIQUE'] ?>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title">Modifier le nom de l'onglet</h5>
            </div>
            <div class="modal-body">
                <div>
                    <label>Nouveau nom</label>
                    <input type="text" class="form-control" id="newName_<?= $formulaire['ID_CAPSULERUBRIQUE'] ?>" required>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                <button type="submit" class="btn btn-success">Sauvegarder</button>
            </div>
        </div>
    </div>
</form>