// @deprecated — Cette suite est maintenue dans prevarisc-migration/cypress/. Toute modification doit y être faite.
// Generated by Cypress Author — 2026-04-27
describe('Dossier — ajout', () => {
    beforeEach(() => {
        cy.login()
    });

    it('Formulaire valide → dossier créé avec les bonnes valeurs', () => {
        const date = Date.now()

        cy.visit('/dossier/ajouter')
        // Symfony form fields: id pattern is dossier_{fieldName}
        cy.get('#dossier_type').select('1');
        cy.get('#dossier_nature').select('1');
        cy.get('#dossier_objet').type(`Dossier Test ${date}`);
        cy.contains('button', 'Créer le dossier').click();

        // Fiche dossier: values are in .right.value divs, no IDs
        cy.contains('Étude').should('exist')
        cy.contains('Permis de construire (PC)').should('exist')
        cy.contains(`Dossier Test ${date}`).should('exist')
    });
});
