// Generated by Cypress Author — 2026-04-27
describe('Dossier — modification', () => {
    beforeEach(() => {
        cy.login()
    })

    it('Libellé modifié → fiche dossier affiche la nouvelle valeur', () => {
        // Navigate directly to avoid brittle href-based selectors on legacy nav links
        cy.visit('/rechercher/dossier')
        cy.get('input[name="objet"]').type('Dossier Test');
        // Two submit buttons exist (header + page) — target the page submit specifically
        cy.get('input[type="submit"][name="Rechercher"]').click();
        cy.contains('Dossier Test').should('exist');
        cy.contains('Dossier Test').click();
        cy.contains('Modifier le dossier').click();

        const newObjet = `Dossier Test ${Date.now()}`;
        cy.get('[name="OBJET_DOSSIER"]').clear().type(newObjet);
        cy.get('input[type="submit"][value="Sauvegarder"]').click();

        cy.get('#OBJET').find('.right.value').should('contain', newObjet)
    });
});
