// Generated by Cypress Author — 2026-04-27
describe('Dossier — recherche', () => {
    beforeEach(() => {
        cy.login()
        cy.visit('/rechercher/dossier')
    })

    it('Page chargée → formulaire de recherche visible', () => {
        cy.contains('Dossiers').should('exist');
        cy.get('[name=Rechercher]').should('exist');
    });

    // Use URL query params to filter by avis — avoids fragile jQuery Chosen interactions.
    it('Filtre "Avis favorable" → seuls les dossiers favorables affichés', () => {
        cy.visit('/rechercher/dossier?avisCommission[]=1')
        cy.get('.avis.F').should('exist')
        cy.get('.avis.D').should('not.exist')
    });

    it('Filtre "Avis défavorable" → seuls les dossiers défavorables affichés', () => {
        cy.visit('/rechercher/dossier?avisCommission[]=2')
        cy.get('.avis.D').should('exist')
        cy.get('.avis.F').should('not.exist')
    });
});
