// Generated by Cypress Author — 2026-05-19
// Tests fonctionnels — Ajout d'un établissement (un test par genre)
// URL migrée : /etablissement/ajouter
// Note : l'autocomplete voies utilise LIBELLE_RUE qui contient l'abréviation du type
// (ex: "R SAINT-JEAN" pour Rue Saint-Jean, "BD CLEMENCEAU" pour Boulevard Clemenceau)
// La commune de test est Louviers (27375, code postal 27400)
describe('Établissement — ajout par genre', () => {
    beforeEach(() => {
        cy.login()
    })

    /**
     * Helper : ajoute une adresse via la modale.
     * Utilise jQuery $.autocomplete (plugin legacy) dont les résultats
     * apparaissent dans un élément .ac_results > ul > li.
     *
     * @param {string} commune - Texte à taper pour la recherche commune (min 2 chars)
     * @param {string} voie - Texte à taper pour la recherche voie (min 2 chars, format LIBELLE_RUE ex: "SAINT-JEAN")
     * @param {string} numero - Numéro de voie
     * @param {string} complement - Complément d'adresse (optionnel)
     */
    function ajouterAdresse(commune, voie, numero, complement) {
        // Intercepter les appels API pour synchroniser le test
        cy.intercept('GET', '/api/2.0/adresse/get_communes*').as('getCommunes')
        cy.intercept('GET', '/api/2.0/adresse/get_voies*').as('getVoies')

        cy.contains('Ajouter une adresse').click()
        // Attendre la fin de l'animation Bootstrap (classe "in" ajoutée après shown.bs.modal)
        cy.get('#adresse-modal-ajout').should('have.class', 'in')

        // Commune (autocomplete jQuery — minChars: 2)
        cy.get('#adresse-modal-ajout input[name="commune_ac"]')
            .should('be.visible')
            .should('not.be.disabled')
            .clear()
            .type(commune, { delay: 80 })
        cy.wait('@getCommunes', { timeout: 10000 })
        cy.get('.ac_results:visible', { timeout: 10000 }).should('exist')
        cy.get('.ac_results:visible ul li').first().click()

        // Voie (autocomplete jQuery — minChars: 2, activée après sélection commune)
        cy.get('#adresse-modal-ajout input[name="voie_ac"]')
            .should('be.visible')
            .should('not.be.disabled')
            .clear()
            .type(voie, { delay: 80 })
        cy.wait('@getVoies', { timeout: 10000 })
        cy.get('.ac_results:visible', { timeout: 10000 }).should('exist')
        cy.get('.ac_results:visible ul li').first().click()

        // Numéro
        cy.get('#adresse-modal-ajout input[name="numero"]')
            .should('not.be.disabled')
            .clear()
            .type(numero)

        if (complement) {
            cy.get('#adresse-modal-ajout input[name="complement"]').clear().type(complement)
        }

        // Coordonnées manuelles (bypass géolocalisation)
        cy.get('#adresse-modal-ajout input[name="lon"]').invoke('val', '1.1667')
        cy.get('#adresse-modal-ajout input[name="lat"]').invoke('val', '49.2167')

        // Sauvegarder l'adresse
        cy.get('#adresse-modal-ajout').contains('Sauvegarder').click()
        cy.get('#adresse-modal-ajout').should('not.have.class', 'in')
    }

    /**
     * Helper : soumet le formulaire et vérifie la création.
     * Intercepte l'appel API defaults_values et auto-confirme la modale si elle apparaît.
     */
    function soumettreEtVerifier(libelle) {
        // Intercepter l'appel qui décide si la modale de confirmation s'affiche
        cy.intercept('POST', '**/defaults_values*').as('defaultsValues')

        // Pré-configurer un listener Bootstrap : si la modale apparaît, auto-confirmer
        cy.window().then(win => {
            win.$('#confirm-modal').on('shown.bs.modal', function () {
                win.$(this).find('input[type="submit"]').trigger('click')
            })
        })

        cy.contains("Ajouter l'établissement").click()

        // Attendre la réponse API (déclenche soit la modale soit le submit direct)
        cy.wait('@defaultsValues')

        // Vérification : redirection vers la fiche de l'établissement créé
        cy.url({ timeout: 15000 }).should('match', /\/etablissement\/\d+/)
        cy.get('h2.page-header, h2').should('contain', libelle)
    }

    /**
     * Helper : sélectionne un élément dans un TomSelect.
     * TomSelect remplace l'input natif par un .ts-control wrapper.
     */
    function tomSelectSearch(inputId, query) {
        cy.get('#' + inputId).siblings('.ts-wrapper').find('.ts-control input').type(query)
        cy.get('#' + inputId).siblings('.ts-wrapper').find('.ts-dropdown .ts-dropdown-content .option').first()
            .should('be.visible').click()
    }

    // ——————————————————————————————————————————————————————————
    // Genre 1 : Site
    // ——————————————————————————————————————————————————————————
    it('Genre Site — création avec informations de base', () => {
        const libelle = `Site E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('SITE-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299000001')
        cy.get('input[name="FAX_ETABLISSEMENT"]').type('0299000002')
        cy.get('input[name="COURRIEL_ETABLISSEMENT"]').type('site@test.fr')

        // Genre = Site (1)
        cy.get('select[name="ID_GENRE"]').select('1')

        // Un Site n'a pas de champ père (caché)
        cy.get('.etablissement_pere').should('not.be.visible')

        soumettreEtVerifier(libelle)
    })

    // ——————————————————————————————————————————————————————————
    // Genre 2 : ERP (Établissement Recevant du Public)
    // ——————————————————————————————————————————————————————————
    it('Genre ERP — création complète avec types, effectifs, plans, adresse, commission', () => {
        const libelle = `ERP E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('ERP-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299100001')
        cy.get('input[name="COURRIEL_ETABLISSEMENT"]').type('erp@test.fr')

        // Genre = ERP (2)
        cy.get('select[name="ID_GENRE"]').select('2')

        // Catégorie
        cy.get('select[name="ID_CATEGORIE"]').should('be.visible').select(1)

        // Périodicité
        cy.get('input[name="PERIODICITE_ETABLISSEMENTINFORMATIONS"]').clear().type('36')

        // Type principal & Activité
        cy.get('select[name="ID_TYPE"]').should('be.visible').select(1)
        cy.get('select[name="ID_TYPEACTIVITE"]').should('be.visible').select(1)

        // Ajouter une activité secondaire
        cy.get('#add_activite_secondaire').click()
        cy.get('#activite_ul li:not(.hide):not(:first)').last().within(() => {
            cy.get('select.type_select').select(1)
            cy.get('select.activite_select').select(1)
        })

        // R143-20
        cy.get('input[name="R14320_ETABLISSEMENTINFORMATIONS"][value="1"]').check()

        // Local à sommeil : Oui (affiche effectif hébergé)
        cy.get('input[name="LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"][value="1"]').check()

        // Effectifs
        cy.get('input[name="EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS"]').clear().type('500')
        cy.get('input[name="EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"]').clear().type('50')
        cy.get('input[name="EFFECTIFHEBERGE_ETABLISSEMENTINFORMATIONS"]').should('be.visible').clear().type('20')

        // Plan d'intervention
        cy.get('#add_plan').click()
        cy.get('#plans_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1)
            cy.get('input[type="text"]').first().type('PLAN-ERP-001')
        })

        // Commission (sélectionner la première disponible)
        cy.get('select[name="ID_COMMISSION"]').select(1)

        // Données pratiques
        cy.get('input[name="NBPREV_ETABLISSEMENT"]').clear().type('2')
        cy.get('input[name="DUREEVISITE_ETABLISSEMENT"]').clear().type('02:30')

        // Adresse
        ajouterAdresse('Louviers', 'CHAMP DE VILLE', '10', 'Bâtiment A')

        soumettreEtVerifier(libelle)

        // Vérifications supplémentaires
        cy.contains('0299100001').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 3 : Cellule
    // ——————————————————————————————————————————————————————————
    it('Genre Cellule — création avec types, effectifs, plans et données pratiques', () => {
        const libelle = `Cellule E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('CEL-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299200001')

        // Genre = Cellule (3)
        cy.get('select[name="ID_GENRE"]').select('3')

        // Type & activité
        cy.get('select[name="ID_TYPE"]').should('be.visible').select(1)
        cy.get('select[name="ID_TYPEACTIVITE"]').should('be.visible').select(1)

        // Effectifs (pas d'effectif hébergé sans local à sommeil)
        cy.get('input[name="EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS"]').clear().type('200')
        cy.get('input[name="EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"]').clear().type('30')

        // Plan
        cy.get('#add_plan').click()
        cy.get('#plans_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1)
            cy.get('input[type="text"]').first().type('PLAN-CEL-001')
        })

        // Données pratiques
        cy.get('input[name="NBPREV_ETABLISSEMENT"]').clear().type('1')
        cy.get('input[name="DUREEVISITE_ETABLISSEMENT"]').clear().type('01:00')

        soumettreEtVerifier(libelle)
        cy.contains('Cellule').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 4 : Habitation
    // ——————————————————————————————————————————————————————————
    it('Genre Habitation — création avec famille et adresse', () => {
        const libelle = `Habitation E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('HAB-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299300001')

        // Genre = Habitation (4)
        cy.get('select[name="ID_GENRE"]').select('4')

        // Famille
        cy.get('select[name="ID_FAMILLE"]').should('be.visible').select(1)

        // Adresse
        ajouterAdresse('Louviers', 'SAINT-JEAN', '5', '')

        soumettreEtVerifier(libelle)
        cy.contains('Habitation').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 5 : IGH
    // ——————————————————————————————————————————————————————————
    it('Genre IGH — création avec classe, effectifs, commission, adresse et plans', () => {
        const libelle = `IGH E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('IGH-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299400001')
        cy.get('input[name="FAX_ETABLISSEMENT"]').type('0299400002')

        // Genre = IGH (5)
        cy.get('select[name="ID_GENRE"]').select('5')

        // Classe IGH
        cy.get('select[name="ID_CLASSE"]').should('be.visible').select(1)

        // Périodicité
        cy.get('input[name="PERIODICITE_ETABLISSEMENTINFORMATIONS"]').clear().type('24')

        // Effectifs (pas d'effectif hébergé sans local à sommeil)
        cy.get('input[name="EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS"]').clear().type('1000')
        cy.get('input[name="EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"]').clear().type('100')

        // Commission
        cy.get('select[name="ID_COMMISSION"]').select(1)

        // Plan
        cy.get('#add_plan').click()
        cy.get('#plans_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1)
            cy.get('input[type="text"]').first().type('PLAN-IGH-001')
        })

        // Adresse
        ajouterAdresse('Louviers', 'CLEMENCEAU', '1', 'Tour A')

        // Données pratiques
        cy.get('input[name="NBPREV_ETABLISSEMENT"]').clear().type('3')
        cy.get('input[name="DUREEVISITE_ETABLISSEMENT"]').clear().type('04:00')

        soumettreEtVerifier(libelle)
        cy.contains('IGH').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 6 : BUP (Bâtiment à Usage Professionnel)
    // ——————————————————————————————————————————————————————————
    it('Genre BUP — création avec ICPE, rubriques, effectifs et adresse', () => {
        const libelle = `BUP E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('BUP-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299500001')

        // Genre = BUP (6)
        cy.get('select[name="ID_GENRE"]').select('6')

        // ICPE coché
        cy.get('input[name="ICPE_ETABLISSEMENTINFORMATIONS"][value="1"]').check()

        // Rubrique ICPE
        cy.get('#add_rubrique').click()
        cy.get('#rubriques_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1) // Rubrique
            cy.get('input[placeholder="Numéro"]').type('4321')
            cy.get('input[placeholder="Nom"]').type('Stockage produits')
            cy.get('input[placeholder="Valeur"]').type('500 T')
            cy.get('select').last().select(1) // Classement
        })

        // Effectifs (pas d'effectif public ni hébergé pour BUP)
        cy.get('input[name="EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"]').clear().type('80')

        // Plan
        cy.get('#add_plan').click()
        cy.get('#plans_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1)
            cy.get('input[type="text"]').first().type('PLAN-BUP-001')
        })

        // Adresse
        ajouterAdresse('Louviers', 'NEUBOURG', '25', 'Zone Industrielle')

        soumettreEtVerifier(libelle)
        cy.contains('BUP').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 7 : Camping
    // ——————————————————————————————————————————————————————————
    it('Genre Camping — création avec emplacements, adresse et plans', () => {
        const libelle = `Camping E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('CAMP-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299600001')
        cy.get('input[name="COURRIEL_ETABLISSEMENT"]').type('camping@test.fr')

        // Genre = Camping (7)
        cy.get('select[name="ID_GENRE"]').select('7')

        // Emplacements camping
        cy.get('input[name="EFFECTIFHABITATION_ETABLISSEMENTINFORMATIONS"]').should('be.visible').clear().type('50')
        cy.get('input[name="EFFECTIFCARAVANE__ETABLISSEMENTINFORMATIONS"]').clear().type('30')
        cy.get('input[name="EFFECTIFEMPLACEMENTNU_ETABLISSEMENTINFORMATIONS"]').clear().type('100')
        cy.get('input[name="EFFECTIFDIVERS_ETABLISSEMENTINFORMATIONS"]').clear().type('20')

        // Vérifier le calcul automatique du total
        cy.get('input[name="EFFECTIFTOTALCAMPING_ETABLISSEMENTINFORMATIONS"]').should('have.value', '200')

        // Plan
        cy.get('#add_plan').click()
        cy.get('#plans_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1)
            cy.get('input[type="text"]').first().type('PLAN-CAMP-001')
        })

        // Adresse
        ajouterAdresse('Louviers', 'NUNGESSER', '1', '')

        soumettreEtVerifier(libelle)
        cy.contains('Camping').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 8 : Manifestation temporaire
    // ——————————————————————————————————————————————————————————
    it('Genre Manifestation temporaire — création avec effectifs, adresse et plans', () => {
        const libelle = `Manif E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('MANIF-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299700001')

        // Genre = Manifestation temporaire (8)
        cy.get('select[name="ID_GENRE"]').select('8')

        // Effectifs
        cy.get('input[name="EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS"]').should('be.visible').clear().type('5000')
        cy.get('input[name="EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"]').clear().type('200')

        // Plan
        cy.get('#add_plan').click()
        cy.get('#plans_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1)
            cy.get('input[type="text"]').first().type('PLAN-MANIF-001')
        })

        // Adresse
        ajouterAdresse('Louviers', 'CHAMP DE VILLE', '1', 'Parc des expositions')

        soumettreEtVerifier(libelle)
        cy.contains('Manifestation').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 9 : IOP (Installation Ouverte au Public)
    // ——————————————————————————————————————————————————————————
    it('Genre IOP — création avec effectifs, adresse et plans', () => {
        const libelle = `IOP E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('IOP-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299800001')
        cy.get('input[name="FAX_ETABLISSEMENT"]').type('0299800002')
        cy.get('input[name="COURRIEL_ETABLISSEMENT"]').type('iop@test.fr')

        // Genre = IOP (9)
        cy.get('select[name="ID_GENRE"]').select('9')

        // Effectifs
        cy.get('input[name="EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS"]').should('be.visible').clear().type('2000')
        cy.get('input[name="EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS"]').clear().type('50')

        // Plan
        cy.get('#add_plan').click()
        cy.get('#plans_tbody tr:not(.hide):not(.prototype)').last().within(() => {
            cy.get('select').first().select(1)
            cy.get('input[type="text"]').first().type('PLAN-IOP-001')
        })

        // Adresse
        ajouterAdresse('Louviers', 'BOMBARD', '3', '')

        soumettreEtVerifier(libelle)
        cy.contains('IOP').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Genre 10 : Zone
    // ——————————————————————————————————————————————————————————
    it('Genre Zone — création avec classement et adresse', () => {
        const libelle = `Zone E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="NUMEROID_ETABLISSEMENT"]').type('ZONE-001')
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299900001')

        // Genre = Zone (10)
        cy.get('select[name="ID_GENRE"]').select('10')

        // Classement de zone
        cy.get('select[name="ID_CLASSEMENT"]').should('be.visible').select(1)

        // Adresse
        ajouterAdresse('Louviers', 'NOVEMBRE', '2', '')

        soumettreEtVerifier(libelle)
        cy.contains('Zone').should('exist')
    })

    // ——————————————————————————————————————————————————————————
    // Test complémentaire : ERP avec établissement père (TomSelect)
    // ——————————————————————————————————————————————————————————
    it('Genre ERP avec père — rattachement à un Site existant via TomSelect', () => {
        const libelle = `ERP Fils E2E ${Date.now()}`

        cy.visit('/etablissement/ajouter')

        // Général
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').type(libelle)
        cy.get('input[name="TELEPHONE_ETABLISSEMENT"]').type('0299110001')

        // Genre = ERP (2)
        cy.get('select[name="ID_GENRE"]').select('2')

        // Rechercher un établissement père via TomSelect
        tomSelectSearch('pere_autocomplete', 'Site E2E')
        cy.get('input[name="ID_PERE"]').should('not.have.value', '')

        // Catégorie + type minimal
        cy.get('select[name="ID_CATEGORIE"]').select(1)
        cy.get('select[name="ID_TYPE"]').select(1)
        cy.get('select[name="ID_TYPEACTIVITE"]').select(1)
        cy.get('input[name="LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"][value="0"]').check()

        // Adresse
        ajouterAdresse('Louviers', 'SAINT-JEAN', '12', '')

        soumettreEtVerifier(libelle)
    })
})
