// Generated by Cypress Author — 2026-04-27
describe('Établissement — modification', () => {
    beforeEach(() => {
        cy.login()
    })

    it('Libellé modifié → fiche établissement affiche la nouvelle valeur', () => {
        // Navigate directly to avoid brittle href-based selectors on legacy nav links
        cy.visit('/rechercher/etablissement')
        // Two name="label" inputs exist (Zend header + page) — target the page search input specifically
        cy.get('input[name="label"].search-query').type('Etablissement Test');
        cy.get('input[type="submit"][name="Rechercher"]').click();
        cy.contains('Etablissement Test').should('exist');
        cy.contains('Etablissement Test').click();
        cy.contains('Modifier la fiche').click();

        const newLabel = `Etablissement Test ${Date.now()}`;
        cy.get('input[name="LIBELLE_ETABLISSEMENTINFORMATIONS"]').clear().type(newLabel);
        cy.contains('Sauvegarder').click();
        cy.contains('Confirmer et sauvegarder les changements').click();

        cy.get('h2.page-header').should('contain', newLabel)
    });
});