// @deprecated — Cette suite est maintenue dans prevarisc-migration/cypress/. Toute modification doit y être faite.
// Generated by Cypress Author — 2026-04-27
describe("Page d'accueil", () => {
    beforeEach(() => {
        cy.login()
        cy.visit('/accueil')
    })

    it("Chargement → au moins un bloc affiché", () => {
        cy.get('.panel').should('have.length.at.least', 1)
    })

    it("Bloc Plat'AU présent → clic sur l'icône déplie le contenu", () => {
        // Bootstrap 3: icons are <span class="glyphicon icon">, not <i>
        cy.contains('.panel-heading', "Dossiers Plat'AU à traiter")
            .find('span.icon')
            .click()
        cy.contains('.panel-heading', "Dossiers Plat'AU à traiter")
            .parents('.panel')
            .find('.panel-body')
            .should('be.visible')
    })
})
