// @deprecated — Cette suite est maintenue dans prevarisc-migration/cypress/. Toute modification doit y être faite.
// Generated by Cypress Author — 2026-04-27
describe("Administration", () => {
    beforeEach(() => {
        cy.login()
        cy.visit('/admin/')
    })

    it("Tableau de bord → informations générales et utilisateurs connectés visibles", () => {
        cy.contains('Informations générales').should('be.visible')
        cy.contains('Utilisateurs connectés').should('be.visible')
    })

    it('Gestion des utilisateurs → liste et actions disponibles', () => {
        cy.contains('a', 'Gestion des utilisateurs').click()

        cy.contains('Général').should('be.visible')
        cy.contains('Ajouter un utilisateur').should('be.visible')
        cy.contains('Créer un groupe').should('be.visible')
        cy.contains('Gérer les droits des groupes').should('be.visible')
        cy.contains('Utilisateurs actifs').should('be.visible')

        cy.contains('a', 'Ajouter un utilisateur').click()
        cy.contains("Ajout d'un utilisateur").should('be.visible')

        cy.go('back')
        cy.contains('a', 'Créer un groupe').click()
        cy.contains("Ajout d'un groupe").should('be.visible')

        cy.go('back')
        cy.contains('a', 'Gérer les droits des groupes').click()
        cy.contains('Matrice des droits').should('be.visible')
    })

    it('Gestion des communes → liste visible', () => {
        cy.contains('a', 'Gestion des communes').click()
        // Texte mis à jour : "Informations sur la commune" → "Informations"
        cy.contains('Informations').should('be.visible')
    })

    it('Fusion des communes → formulaire visible', () => {
        cy.contains('a', 'Fusion des communes').click()
        cy.contains('Fusion des communes').should('be.visible')
    })

    it('Couches cartographiques → liste et actions disponibles', () => {
        cy.contains('a', 'Gestion des couches cartographiques').click()

        cy.contains('Ajouter une couche personnalisée').should('be.visible')
        cy.contains('Ajouter une couche IGN').should('be.visible')
        cy.contains("Changer l'ordre des couches").should('be.visible')

        cy.contains('a', 'Ajouter une couche personnalisée').click()
        cy.contains("Ajout d'une couche cartographique").should('be.visible')

        cy.go('back')
        cy.contains('a', 'Ajouter une couche IGN').click()
        cy.contains("Ajout d'une couche cartographique IGN").should('be.visible')
    })

    it('Commissions → page de liste chargée', () => {
        cy.contains('a', 'Gestion des commissions').click()
        cy.contains('Gérer les commissions').should('be.visible')
    })

    it('Documents types → liste et ajout disponibles', () => {
        cy.contains('a', 'Gestion des documents').click()

        // "Visible après verrouillage" — typo 'vérrouillage' corrigé en 'verrouillage' dans le template
        cy.contains('verrouillage').should('be.visible')
        cy.contains('button', 'Ajouter un document').click()
        cy.contains('Ajouter un document type').should('be.visible')
    })

    it('Tableau des périodicités → types ERP et IGH visibles', () => {
        cy.contains('a', 'Tableau des périodicités').click()
        cy.contains('ERP').should('be.visible')
        cy.contains('IGH').should('be.visible')
    })

    it('Groupements de communes → liste et création disponibles', () => {
        cy.contains('a', 'Groupements de communes').click()

        cy.contains('Général').should('be.visible')
        cy.contains('button', 'Créer un nouveau groupement').click()
        // Titre de la modale mis à jour : "Création d'un nouveau groupement" → "Ajouter un groupement"
        cy.contains('Ajouter un groupement').should('be.visible')
    })

    it('Messages des alertes → balises disponibles', () => {
        cy.contains('a', 'Messages des alertes').click()

        cy.contains('Message de changement de statut').should('be.visible')
        cy.contains("Message de changement d'avis").should('be.visible')
        cy.contains('Message de changement de classement').should('be.visible')
        cy.contains('Voir les balises disponibles').click()
        cy.contains('Liste des balises disponibles').should('be.visible')
    })

    it('Formulaires descriptifs → liste des formulaires visible', () => {
        cy.contains('a', 'Formulaires').click()

        // Titres des formulaires sont dynamiques — vérifier les sections stables
        cy.contains('h2', "Onglets de l'établissement").should('be.visible')
    })
})