// @deprecated — Cette suite est maintenue dans prevarisc-migration/cypress/. Toute modification doit y être faite.
// Generated by Cypress Author — 2026-04-27
describe('Authentification', () => {
    it('Identifiants valides → redirection vers l\'accueil', () => {
        cy.visit('/session/login');
        cy.get('[name=prevarisc_login_username]').type(Cypress.env('username'));
        cy.get('[name=prevarisc_login_passwd]').type(Cypress.env('password'));
        cy.get('#Connexion').click();
        cy.contains('Bonjour ROOT').should('exist');
    });

    it('Identifiants invalides → message d\'erreur affiché', () => {
        cy.visit('/session/login');
        cy.get('[name=prevarisc_login_username]').type('wrongUser');
        cy.get('[name=prevarisc_login_passwd]').type('wrongPass');
        cy.get('#Connexion').click();
        cy.contains('Erreur d\'authentification').should('exist');
    });
});
