// Generated by Cypress Author — 2026-04-27
// Tests fonctionnels pour les sections Changelog et Prescriptions admin
describe('Changelog', () => {
    beforeEach(() => {
        cy.login()
    })

    it('Page chargée → titre "Nouveautés & corrections" visible', () => {
        cy.visit('/changelog')
        cy.contains('h1', 'Nouveautés').should('be.visible')
    })
})

describe('Administration — prescriptions', () => {
    beforeEach(() => {
        cy.login()
        cy.visit('/admin/prescriptions')
    })

    it('Page chargée → gestion des prescriptions visible', () => {
        cy.contains('Gestion des prescriptions').should('be.visible')
    })

    it('Navigation prescriptions → textes applicables accessibles', () => {
        cy.visit('/admin/textes-applicables')
        cy.contains('Gestion des textes applicables').should('be.visible')
    })

    it('Navigation prescriptions → articles accessibles', () => {
        cy.visit('/admin/prescriptions/articles/')
        // Page should load without error (status checked via smoke) — verify heading
        cy.get('body').should('not.contain', 'Internal Server Error')
    })
})
