<h2 class='label label-important'><?= ucfirst($this->element).'s' ?> supprimés</h2>
<div class="muted">
    <small>Nombre total d'éléments : <?= count($this->data) ?></small>
</div>
<ul class='gridRetablir'>
    <?php foreach($this->data as $deletedElement) : ?>
        <p><?= $deletedElement['USERNAME_UTILISATEUR'] ?></p>
        <div class='linkDisabled'>
            <?= $this->partial("search/results/{$this->element}.phtml", $deletedElement) ?>
        </div>
        <a
            class='btn-small'
            href=<?= sprintf(
                "/{$this->element}/retablir-{$this->element}/%s/%d",
                'id'.ucfirst($this->element),
                $deletedElement['ID_'.strtoupper($this->element)]
            ) ?>
        >
            <em class="icon-ok icon-black"></em>
            Rétablir
        </a>
    <?php endforeach ?>
</ul>
