<h2 class='label label-important'>Dossiers supprimés</h2>
<div class="muted">
    <small>Nombre total d'éléments : <?= count($this->data) ?></small>
</div>
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>Supprimé par</th>
            <th>Nom du dossier</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $deletedElement) : ?>
            <tr>
                <td>
                    <p><?= $deletedElement['USERNAME_UTILISATEUR'] ?></p>
                </td>

                <td>
                    <?php if (!empty($deletedElement['OBJET_DOSSIER'])):
                        if (strlen($deletedElement['OBJET_DOSSIER']) > 70):
                            $deletedElement['OBJET_DOSSIER'] = substr($deletedElement['OBJET_DOSSIER'], 0, 70).'(...)';
                        endif;
                    else:
                        $deletedElement['OBJET_DOSSIER'] = '';
                    endif;

                    $linkTitleVariables = array_values(
                        array_filter(
                            array(
                                $deletedElement['LIBELLE_DOSSIERTYPE'],
                                $deletedElement['LIBELLE_DOSSIERNATURE'],
                                $deletedElement['OBJET_DOSSIER']
                            )
                        )
                    );

                    $fulltext = '';
                    for ($i = 0; $i < count($linkTitleVariables); $i++):
                        $fulltext .= $linkTitleVariables[$i];

                        if ($i !== (count($linkTitleVariables) - 1)):
                            $fulltext .= ' - ';
                        endif;
                    endfor;
                    ?>

                    <a href='/dossier/index/id/<?php echo $deletedElement['ID_DOSSIER'] ?>' title='<?php echo htmlspecialchars($fulltext, ENT_QUOTES) ?>'>
                        <?php if (null !== $deletedElement['LIBELLE_ETABLISSEMENTINFORMATIONS']): ?>
                            <?php echo '[' . $deletedElement['LIBELLE_ETABLISSEMENTINFORMATIONS'] . '] ' ?>
                        <?php endif;

                        echo $fulltext;
                        ?>
                    </a>
                </td>

                <td>
                    <a
                        class='btn-small'
                        href=<?= '/dossier/retablir-dossier/idDossier/'.$deletedElement['ID_DOSSIER'] ?>
                    >
                        <em class="icon-ok icon-black"></em>
                        Rétablir le dossier
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
