<div class="muted">
    <small>Nombre total d'éléments : <?= count($this->data) ?></small>
</div>

<?php if (count($this->data) > 0): ?>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th class="whitespace-nowrap">Supprimé par</th>
                <th>Nom de l'établissement</th>
                <th class="whitespace-nowrap"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $deletedElement) : ?>
                <tr>
                    <td class="whitespace-nowrap">
                        <p><?= $deletedElement['USERNAME_UTILISATEUR'] ?></p>
                    </td>

                    <td class='linkDisabled'>
                        <?= $deletedElement['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>
                        <?php if ('' !== $deletedElement['LIBELLE_COMMUNE']): ?>
                            - <?= $deletedElement['LIBELLE_COMMUNE'] ?>
                        <?php endif ?>
                    </td>

                    <td class="whitespace-nowrap">
                        <a
                            class='btn-small'
                            href=<?= '/etablissement/retablir-etablissement/idEtablissement/'.$deletedElement['ID_ETABLISSEMENT'] ?>
                        >
                            <em class="icon-ok icon-black"></em>
                            Rétablir l'établissement
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
