<h2>Fusion des communes</h2>

<?php if ($this->downloadComplete): ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Le fichier a bien été chargé
    </div>
<?php endif ?>

<?php if ($this->hasErrors): ?>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        La commande a retourné des erreurs, veuillez vérifier les logs d'erreur
    </div>
<?php endif ?>

<?= $this->form ?>
