SET NAMES 'utf8';

ALTER TABLE `etablissementinformations` CHANGE `R12320_ETABLISSEMENTINFORMATIONS` `R14320_ETABLISSEMENTINFORMATIONS` tinyint(1);
UPDATE `prescriptionarticleliste` SET `LIBELLE_ARTICLE` = 'R. 143-20' WHERE `LIBELLE_ARTICLE` LIKE 'R. 123-20';
UPDATE `prescriptionarticleliste` SET `LIBELLE_ARTICLE` = 'R. 143-16' WHERE `LIBELLE_ARTICLE` LIKE 'R. 123-16';