SET NAMES 'utf8';

ALTER TABLE `dossier` ADD COLUMN `DATE_NOTIFICATION` DATETIME NULL DEFAULT NULL;
ALTER TABLE `piecejointe` ADD COLUMN `DATE_NOTIFICATION` DATETIME NULL DEFAULT NULL;
ALTER TABLE `utilisateur` ADD COLUMN `DERNIERE_VISITE_DASHBOARD` DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `utilisateur` ADD COLUMN `DERNIERE_VISITE_PIECES_DOSSIER` DATETIME DEFAULT CURRENT_TIMESTAMP;