CREATE TABLE avisderogations(
   ID_AVIS_DEROGATION BIGINT,
   TYPE_AVIS_DEROGATIONS TINYINT NOT NULL,   
   TITRE VARCHAR(50),
   INFORMATIONS TEXT,
   IS_FAVORABLE TINYINT,
   ID_DOSSIER_LIE BIGINT,
   DISPLAY_HISTORIQUE TINYINT,
   PRIMARY KEY(ID_AVIS_DEROGATION)
);
