SET NAMES 'utf8';

ALTER TABLE `piecejointe` ADD COLUMN `TYPE` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `piecejointe` ADD COLUMN `SOUS_TYPE` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `piecejointe` ADD COLUMN `NATURE` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `piecejointe` ADD COLUMN `DATE_DEPOT` DATE NULL DEFAULT NULL;