<form class="form-horizontal span8" method="post">
    <input class="btn btn-success pull-right" type='submit' value='Ajouter l&apos;avis'/>

    <input type='hidden' name='ID_DOSSIER' value='<?= $this->idDossier ?>' />

    <!-- TODO Faire une table typeavisderogation ? -->
    <div class="control-group">
        <label class="control-label" for="inputType">Type</label>
        <div class="controls">
            <select name="TYPE" required>
                <option value='Avis'>
                    Avis
                </option>
                <option value='Dérogation'>
                    Dérogation
                </option>
            </select>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputTitre">Titre</label>
        <div class="controls">
            <input name="TITRE" type="text" id="inputTitre" required>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputInformations">Informations</label>
        <div class="controls">
            <textarea name="INFORMATIONS"></textarea>
        </div>
    </div>

    <div class="control-group">
        <p class="control-label">Avis</p>
        <div class="controls">
            <select name="AVIS" class="span4">
                <?php foreach ($this->listeAvis as $avis): ?>
                    <option value='<?= $avis["ID_AVIS"] ?>'><?= $avis['LIBELLE_AVIS'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <div class="control-group">
        <p class="control-label">Avis/Dérogation levé(e):</p>
        <?= $this->partial('dossier/results/avisderogation/dossier.phtml', ['DOSSIERS_ETAB' => $this->listDossierEtab, 'ID_DOSSIER_LIE' => $this->ID_DOSSIER_LIE]); ?>
    </div>

    <div class="control-group">
        <label class="control-label"for="DISPLAY_HISTORIQUE">Afficher dans l'historique de l'établissement</label>
        <div class="controls">
            <input type='hidden' name='DISPLAY_HISTORIQUE' value='0'>
            <input
                type="checkbox"
                id="DISPLAY_HISTORIQUE"
                name="DISPLAY_HISTORIQUE"
                value='1'
            >
        </div>
    </div>
</form>

<?= $this->partialLoop("dossier/results/avis-et-derogations.phtml", $this->arrayAvisDerogations); ?>
