<form class="form-horizontal span8" method="post">
    <input class="btn btn-success pull-right" type='submit' value='Ajouter l&apos;avis'/>

    <input type='hidden' name='ID_DOSSIER' value='<?= $this->idDossier ?>' />

    <div class="control-group">
        <label class="control-label" for="inputType">Type</label>
        <div class="controls">
            <select id="inputType" name="TYPE" required>
                <option value='Avis'>
                    Avis
                </option>
                <option value='Dérogation'>
                    Dérogation
                </option>
            </select>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputTitre">Titre</label>
        <div class="controls">
            <input name="TITRE" type="text" id="inputTitre" required>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputObjet">Objet</label>
        <div class="controls">
            <textarea id="inputObjet" name="OBJET"></textarea>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputJustification">Justification</label>
        <div class="controls">
            <textarea id="inputJustification" name="JUSTIFICATION"></textarea>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputArticlesConcernes">Article(s) concerné(s)</label>
        <div class="controls">
            <textarea id="inputArticlesConcernes" name="ARTICLES_CONCERNES"></textarea>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputMesuresCompensatoiresProposees">Mesure(s) compensatoire(s) proposée(s)</label>
        <div class="controls">
            <textarea id="inputMesuresCompensatoiresProposees" name="MESURES_COMPENSATOIRES_PROPOSEES"></textarea>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputAnalyseDeRisque">Analyse de risque</label>
        <div class="controls">
            <textarea id="inputAnalyseDeRisque" name="ANALYSE_DE_RISQUE"></textarea>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputAvis">Avis</label>
        <div class="controls">
            <select id="inputAvis" name="AVIS">
                <?php foreach ($this->listeAvis as $avis): ?>
                    <option value='<?= $avis["ID_AVIS"] ?>'><?= $avis['LIBELLE_AVIS'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Avis/Dérogation levé(e):</label>
        <?=
            $this->partial(
                'dossier/results/avisderogation/liste-dossier.phtml',
                [
                    'listeDossierParType' => $this->listDossierEtab
                ]
            );
        ?>
    </div>

    <input class="btn btn-success pull-right" type='submit' value='Ajouter l&apos;avis'/>

    <div class="control-group">
        <label class="control-label" for="DISPLAY_HISTORIQUE">Afficher dans l'onglet de l'établissement</label>
        <div class="controls">
            <input type='hidden' name='DISPLAY_HISTORIQUE' value='0'>
            <input
                type="checkbox"
                id="DISPLAY_HISTORIQUE"
                name="DISPLAY_HISTORIQUE"
                value='1'
            >
        </div>
    </div>
</form>

<?= $this->partialLoop("dossier/results/avis-et-derogations.phtml", $this->arrayAvisDerogations); ?>
