<h4 class="h4_subtitle">Avis / Dérogation <strong> ID BLOCK : <?= $this->avisDerogations['ID_AVIS_DEROGATION']?></strong></h4>
<form  class="container-fluid" method="post">
    <div class="btn-group pull-right">
        <a class="btn" href="<?= $this->url(['controller' => 'dossier', 'action' => 'avis-et-derogations', 'id' => $this->avisDerogations['ID_DOSSIER']], false, true) ?>">Annuler modification</a>
        <input type="submit" class="btn btn-success" href=<?= "/dossier/avis-et-derogations/id/". $this->avisDerogations['ID_DOSSIER'] ?> value="Sauvegarder">
    </div>
    <div class="row">
        <p class="span2">Type</p>
        <!--Generation liste des avis-->
        <select name="TYPE_AVIS_DEROGATIONS" required="required">
            <option value="1" <?= 1 === $this->avisDerogations['TYPE_AVIS_DEROGATIONS'] ? 'selected' : '' ?> >
                Avis
            </option>
            <option value="2" <?= 2 === $this->avisDerogations['TYPE_AVIS_DEROGATIONS'] ? 'selected' : '' ?> >
                Dérogations
            </option>
        </select>
    </div>
    <div class="row">
        <p class="span2">Titre</p>
        <input name="TITRE" class="span4" type="text" placeholder="votre titre" required="required" value='<?= $this->avisDerogations['TITRE'] ?>' >
    </div>
    <div class="row">
        <p>Informations</p>
        <textarea name="INFORMATIONS"><?= $this->avisDerogations['INFORMATIONS'] ?></textarea>
    </div>
    <div class="row">
        <p class="span2">Avis</p>
        <select name="AVIS" class="span4" required="required">       
            <option value="1" <?= $this->avisDerogations['AVIS'] === 1 ? 'selected':''  ?>  >Favorable</option>
            <option  value="0" <?=  $this->avisDerogations['AVIS'] === 0 ? 'selected':'' ?> >Défavorable</option>
        </select>
    </div>
    <div class="row">
        <h2 class="h4_subtitle span3">Avis/Dérogation levé(e):</h2>
    </div>   

    <div class="row">
        <?= $this->partial('dossier/results/avisderogation/dossier.phtml', ['DOSSIERS_ETAB' => $this->listDossierEtab, 'ID_DOSSIER_LIE' => $this->avisDerogations['ID_DOSSIER_LIE']]); ?>
    </div>

    <div class="row" style="display:flex">
        <input type='hidden' name='DISPLAY_HISTORIQUE' value='0'>
        <input  type="checkbox" 
                id="DISPLAY_HISTORIQUE" 
                name="DISPLAY_HISTORIQUE"
                value='1'
                <?= ($this->avisDerogations['DISPLAY_HISTORIQUE'] == true ? 'checked' : '') ?> 
        >
        <label for="DISPLAY_HISTORIQUE">Afficher l'historique de l'établissement</label>
    </div>




</form>
