<!-- TODO Revoir le visuel -->
<h4 class="h4_subtitle">Avis / Dérogation</h4>
<form class="container-fluid" method="post">
    <div class="btn-group pull-right">
        <a class="btn" href="<?= $this->url(['controller' => 'dossier', 'action' => 'avis-et-derogations', 'id' => $this->avisDerogations['ID_DOSSIER']], false, true) ?>">Annuler modification</a>
        <input type="submit" class="btn btn-success" value="Sauvegarder" />
    </div>

    <div class="row">
        <p class="span2">Type</p>
        <!--Generation liste des avis-->
        <select name="TYPE" required>
            <option value="Avis" <?= 'Avis' === $this->avisDerogations['TYPE'] ? 'selected' : '' ?>>
                Avis
            </option>
            <option value="Dérogation" <?= 'Dérogation' === $this->avisDerogations['TYPE'] ? 'selected' : '' ?>>
                Dérogation
            </option>
        </select>
    </div>

    <div class="row">
        <p class="span2">Titre</p>
        <input name="TITRE" class="span4" type="text" required value='<?= $this->avisDerogations['TITRE'] ?>' >
    </div>

    <div class="row">
        <p>Informations</p>
        <textarea name="INFORMATIONS"><?= $this->avisDerogations['INFORMATIONS'] ?></textarea>
    </div>

    <div class="row">
        <p class="span2">Avis</p>
        <select name="AVIS" class="span4">
            <?php foreach ($this->listeAvis as $avis): ?>
                <option value='<?= $avis["ID_AVIS"] ?>' <?= $this->avisDerogations['AVIS'] === $avis['ID_AVIS'] ? 'selected' : '' ?>><?= $avis['LIBELLE_AVIS'] ?></option>
            <?php endforeach ?>
        </select>
    </div>

    <div class="row">
        <h2 class="h4_subtitle span3">Avis/Dérogation levé(e):</h2>
    </div>

    <div class="row">
        <?= $this->partial('dossier/results/avisderogation/dossier.phtml', ['DOSSIERS_ETAB' => $this->listDossierEtab, 'ID_DOSSIER_LIE' => $this->avisDerogations['ID_DOSSIER_LIE']]); ?>
    </div>

    <div class="row" style="display:flex">
        <input type='hidden' name='DISPLAY_HISTORIQUE' value='0'>
        <input
            type="checkbox"
            id="DISPLAY_HISTORIQUE"
            name="DISPLAY_HISTORIQUE"
            value='1'
            <?= ($this->avisDerogations['DISPLAY_HISTORIQUE'] == true ? 'checked' : '') ?>
        >
        <label for="DISPLAY_HISTORIQUE">Afficher dans l'historique de l'établissement</label>
    </div>
</form>
