<div class="btn-group pull-right">
    <a class="btn" href=<?php echo ("/dossier/avis-et-derogations/id/". $this->idDossier)?>>Annuler modification</a>
    <a class="btn btn-success" href=<?php echo ("/dossier/avis-et-derogations/id/". $this->idDossier)?>>Sauvegarder</a>
</div>
<?php echo $this->partialLoop("dossier/results/avis-et-derogations-edit.phtml", $this->arrayAvisDerogations); ?>
<h4><a href=""> + Ajouter un avis de dérogation</a></h4>