<form action='<?= $this->url(array('action' => 'edit-verifications-techniques')) ?>' method='post' class='form-horizontal'>
    <div class='pull-right' >
        <div class="btn-group">
            <a class='btn' href="<?= $this->url(array('action' => 'verifications-techniques')) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>

    <h3>Modification des descriptifs</h3>
    <h4 class='h4_subtitle'>Descriptif</h4>
    
    <div class='row-fluid'>
        <div class='span10'>
            <?php foreach ($this->rubriques as $key => $rubrique):
                if (($key % 4) === 0): ?>
                    <div class='row-fluid'>
                <?php endif;

                echo $this->partial('formulaire/partials/partial-edit-rubrique-display.phtml', $rubrique);   
                
                if ((($key % 4) === 3) || ($rubrique === end($this->rubriques))): ?>
                    </div>
                <?php endif;
            endforeach ?>
        </div>
    </div>

    <!-- TODO Faire la même avec des partials loops -->
    <?php foreach ($this->rubriques as $rubrique): ?>
        <div id='afficher_rubrique-<?= $rubrique['ID_RUBRIQUE'] ?>' class="<?= boolval($rubrique['DISPLAY']) === false ? 'hide' : '' ?>">
            <h4 class='h4_subtitle'><?= $rubrique['NOM'] ?></h4>

            <?php if (!empty($rubrique['CHAMPS'])):
                foreach ($rubrique['CHAMPS'] as $champ): ?>
                    <div class='control-group'>
                        <label for='champ-<?= $champ["ID_CHAMP"] ?>' class='control-label'>
                            <strong><?= $champ['NOM'] ?></strong>
                        </label>
                        <div class='controls'>
                            <?php switch ($champ['ID_TYPECHAMP']) {
                                // Texte
                                case 1: ?>
                                    <input
                                        type='text'
                                        name='champ-<?= $champ["ID_CHAMP"] ?>'
                                        value='<?= $champ["VALEUR"] ?>'
                                    >
                                <?php break;
                                // Texte long
                                case 2: ?>
                                    <textarea name='champ-<?= $champ["ID_CHAMP"] ?>'><?= $champ["VALEUR"] ?></textarea>
                                <?php break;
                                // Liste
                                case 3: ?>
                                    <select name='champ-<?= $champ["ID_CHAMP"] ?>'>
                                        <option selected value>Sélectionnez un élément</option>
                                        <?php foreach($this->champsvaleurliste[$champ['ID_CHAMP']] as $champvaleurliste): ?>
                                            <option
                                                value="<?= $champvaleurliste['VALEUR'] ?>"
                                                <?= $champvaleurliste['VALEUR'] === $champ['VALEUR'] ? 'selected' : '' ?>
                                            >
                                                <?= $champvaleurliste['VALEUR'] ?>
                                            </option>
                                        <?php endforeach ?>
                                    </select>
                                <?php break;
                                // Nombre
                                case 4: ?>
                                    <input type='number' name='champ-<?= $champ["ID_CHAMP"] ?>' min='0' value='<?= $champ["VALEUR"] ?>'>
                                <?php break;
                                // Case à cocher
                                case 5: ?>
                                    <input
                                        type="hidden"
                                        name='champ-<?= $champ["ID_CHAMP"] ?>'
                                        value="0"
                                    >
                                    <input
                                        type="checkbox"
                                        name='champ-<?= $champ["ID_CHAMP"] ?>'
                                        value="1"
                                        <?= $champ['VALEUR'] ? 'checked' : '' ?>
                                    >
                                <?php break;       
                                default:
                                    break;
                            } ?>
                        </div>
                    </div>
                <?php endforeach;
            else:
                echo $this->partial('formulaire/partials/partial-information-manquante.phtml', [
                    'message' => 'Aucun champ renseigné. Contactez un administrateur Prevarisc.'
                ]);
            endif ?>
        </div>
    <?php endforeach ?>
</form>