<form action='<?= $this->url(array('action' => 'edit-verifications-techniques')) ?>' method='post' class='form-horizontal'>
    <div class='pull-right' >
        <div class="btn-group">
            <a class='btn' href="<?= $this->url(array('action' => 'verifications-techniques')) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>

    <h3>Modification des vérifications techniques</h3>
    <h4 class='h4_subtitle'>Rubriques</h4>

    <div class='row-fluid'>
        <div class='span10'>
            <?php foreach ($this->rubriques as $key => $rubrique): ?>
                <?=  $this->partial('formulaire/partials/partial-edit-rubrique-display.phtml', $rubrique); ?>
            <?php endforeach ?>
        </div>
    </div>
    
    <?= 
        $this->partial('formulaire/partials/partial-form-custom.phtml', [
                'corpsformulaire' => $this->corpsformulaire,
                'valeurformulaire' => $this->valeurformulaire,
                'rubriquedisplay' => $this->rubriques,
                'canWrite' => true
            ]); 
    ?>
    
</form>
