<form action='<?= $this->url(array('action' => 'edit-verifications-techniques')) ?>' method='post' class='form-horizontal'>
    <div class='action-buttons pull-right'>
        <div class="btn-group">
            <a class='btn' href="<?= $this->url(array('action' => 'verifications-techniques')) ?>" data-do-not-unload>Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder' data-do-not-unload>
        </div>
    </div>

    <h3>Modification des vérifications techniques</h3>
    <div class="form-layout">
        <?= $this->partial('formulaire/_table_of_content.phtml', [
            'rubriques' => $this->rubriques,
        ]) ?>

        <main>
            <?= $this->partial('formulaire/partials/partial-form-custom.phtml', [
                'rubriques' => $this->rubriques,
                'champsvaleurliste' => $this->champsvaleurliste,
                'canWrite' => true
            ]); ?>
        </main>
    </div>

    <?= $this->partial('formulaire/_modal_table_of_content.phtml', [
        'rubriques' => $this->rubriques
    ]) ?>
</form>

<button
    id="show-toc"
    type="button"
    class="btn"
    title="Afficher les rubriques"
>
    <i class="icon-filter"></i>
</button>
