<form action='<?= $this->url(array('action' => 'effectifs-degagements-dossier-edit')) ?>' method='post' class='form-horizontal'>
    <div class='action-buttons pull-right'>
        <div class="btn-group">
            <a class='btn' href="<?= $this->url(array('action' => 'effectifs-degagements-dossier')) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>

    <h3>Modification des effectifs et dégagements</h3>
    <h4 class='h4_subtitle'>Rubriques</h4>

    <div class='row-fluid'>
        <div class='span12'>
            <?php foreach (array_chunk($this->rubriques, 4) as $chunkedRubriques): ?>
                <div class='row-fluid'>
                    <?php foreach ($chunkedRubriques as $rubrique):
                        echo $this->partial('formulaire/partials/partial-edit-rubrique-display.phtml', $rubrique);
                    endforeach ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <?= $this->partial('formulaire/partials/partial-form-custom.phtml', [
        'rubriques' => $this->rubriques,
        'champsvaleurliste' => $this->champsvaleurliste,
        'canWrite' => true
    ]); ?>
</form>
