<form action=/dossier/effectifs-degagements-dossier-edit/id/<?php echo $this->idDossier?> method="get">
    <div class='pull-right'>
        <input class="btn btn-success" type='submit' value="Modifier effectifs dégagements"/>
    </div>

    <h3>Effectifs :</h3>
    <?php
        if (isset($this->EffectifDegagement[0]["DESCRIPTION_EFFECTIF"])) {
            echo $this->EffectifDegagement[0]["DESCRIPTION_EFFECTIF"];
        } else {
            echo "Aucune description";
        }
    ?>

    <h3>Dégagements :</h3>
    <?php
        if (isset($this->EffectifDegagement[0]["DESCRIPTION_DEGAGEMENT"])) {
            echo $this->EffectifDegagement[0]["DESCRIPTION_DEGAGEMENT"];
        } else {
            echo "Aucune description";
        }
    ?>
</form>

<script type='text/javascript'>
    tinymce.init({
        selector: '.tinyarea',
        height: 150,
        menubar: false,
        statusbar: false,
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table contextmenu paste code'
        ],
        toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link',
        content_css: [
            '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
            '//www.tinymce.com/css/codepen.min.css'
        ]
    });
</script>