<div id="bddedit" class="content">
                <h4>Ajouter une adresse depuis BDD</h4>
                <dl class='dl-horizontal'>
                    <dt>Ville</dt>
                    <dd>
                        <input name='commune_ac' type='text' placeholder='Nom de la commune ou code postal ...' />
                        <input name='code_insee' type='hidden' />
                        <input name='code_postal' type='hidden' />
                    </dd>

                    <dt>Voie</dt>
                    <dd>
                        <input type='text' name='voie_ac' placeholder='Nom de la voie ...' />
                        <input type='hidden' name='type_voie' />
                        <input type='hidden' name='voie' />
                    </dd>

                    <dt>Numéro</dt>
                    <dd>
                        <input class="input-small" type='text' name='numero' placeholder='Numéro ...' />
                    </dd>

                    <dt>Complément d'adresse</dt>
                    <dd>
                        <input type='text' name='complement' placeholder="Complément d'adresse" />
                    </dd>

                    <dt>Type de l'adresse</dt>
                    <dd>
                        <select name="type_adresse">
                            <option>Adresse postale</option>
                        </select>
                    </dd>

                    <dt>Géolocalisation</dt>
                    <dd>
                        <?php if ($this->key_ign !== null) : ?>
                            <button id="geolocme" type='button' class='btn btn-small'><i class="icon-map-marker"></i> Géolocaliser cette adresse (Geoportail)</button>
                        <?php endif; ?>
                        <br/>
                        <small>Résultat : <span class='result'>Inconnu</span></small>
                    </dd>

                    <dt>Longitude</dt>
                    <dd>
                        <input id="addressLongitude" type='text' name='lon' />
                    </dd>

                    <dt>Latitude</dt>
                    <dd>
                        <input id="addressLatitude" type='text' name='lat' />
                    </dd>
                </dl>
                <?php if ($this->key_ign !== null): ?>
                    <div id="edit-geoportail-container" style="height: 400px;"></div>
                <?php endif; ?>
            </div>