<form id="adresse-modal-edit" class="modal hide adresse fase adresse-modal-edit" method='post'>
    <input type='hidden' name='idAdresse' value=""/>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Modifier une adresse</h3>
    </div>

    <div class="modal-body">
        <dl class='dl-horizontal'>
            <dt>Ville</dt>
            <dd>
                <input name='commune_ac' type='text' placeholder='Nom de la commune ou code postal ...' />
                <input name='code_insee' type='hidden' />
                <input name='code_postal' type='hidden' />
            </dd>

            <dt>Voie</dt>
            <dd>
                <input type='text' name='voie_ac' placeholder='Nom de la voie ...' disabled />
                <input type='hidden' name='type_voie' />
                <input type='hidden' name='voie' />
            </dd>

            <dt>Numéro</dt>
            <dd>
                <input class="input-small" type='text' name='numero' placeholder='Numéro ...' disabled />
            </dd>

            <dt>Complément d'adresse</dt>
            <dd>
                <input type='text' name='complement' placeholder="Complément d'adresse" disabled />
            </dd>

            <dt>Type de l'adresse</dt>
            <dd>
                <select>
                    <option>Adresse postale</option>
                </select>
            </dd>

            <dt>Géolocalisation</dt>
            <dd>
                <?php if ($this->key_ign != null) : ?><button id="geolocme" class='btn btn-small'><i class="icon-map-marker"></i> Géolocaliser cette adresse (Geoportail)</button><?php endif ?>
                <?php if ($this->geoconcept_url != null) : ?><button id="geolocme-geoconcept" class='btn btn-small'><i class="icon-map-marker"></i> Géolocaliser cette adresse (Geoconcept)</button><?php endif ?>
                <button id="geolocme_nominatim" class='btn btn-small'><i class="icon-map-marker"></i> Géolocaliser cette adresse (Nominatim)</button>
                <br/>
                <small>Résultat : <span class='result'>Inconnu</span></small>
            </dd>

            <dt>Longitude</dt>
            <dd>
                 <input id="addressLongitude" type='text' name='lon' />
            </dd>

            <dt>Latitude</dt>
            <dd>
                 <input id="addressLatitude" type='text' name='lat' />
            </dd>
        </dl>
        <?php if ($this->key_ign != null): ?>
            <div id="geoportail-container" style="height: 400px;"></div>

            <!-- Déplacement du bouton FullScreen (sinon supperposé avec le gestionnaire de couches) -->
            <style>
                .ol-full-screen {right:9px; top:49px}
            </style>
        <?php endif ?>

        <?php if ($this->geoconcept_url != null) : ?>
            <div id='geoconcept-container' style="height: 400px; width: 100%"></div>
            <script type="text/javascript" src="/js/geoconcept/OpenLayers.js"></script>
            <script type="text/javascript" src="/js/geoconcept/proj4js.js"></script>
            <script type="text/javascript" src="/js/geoconcept/htc-lite.js"></script>
            <?php if ($projection = getenv('PREVARISC_PLUGIN_GEOCONCEPT_PROJECTION')): ?>
            <script type="text/javascript" src="/js/geoconcept/defs/<?php echo $projection ?>.js"></script>
            <?php endif ?>
            <script type="text/javascript" src="/js/geoconcept/geoconcept.js"></script>
            <link rel="stylesheet" href="/css/geoconcept/htc.css"/>
        <?php endif ?>
    </div>

    <div class="modal-footer">
        <a href="#" data-dismiss="modal" class="btn">Annuler</a>
        <button id='submit-adresse-edit' class="btn btn-success"> Modifier </a>
    </div>
</form>

<script>
    window.onload = function(){
        $('#submit-adresse-edit').click(function (e) {
            e.preventDefault()
            const dataToPush = {}

            $('#adresse-modal-edit :input').each(idx => {
                dataToPush[$('#adresse-modal-edit :input')[idx].name] = $('#adresse-modal-edit :input')[idx].value
            })

            $.post("/etablissement/update-adresse", dataToPush,
                function (data, textStatus, jqXHR) {
                    console.log("Response is ",data)
                }
            );
        });
    }
</script>
