<tr <?= $this->adresse === null ? "id='prototype_adresse' class='prototypes hide'" : "class='adresse'" ?>>
    <td id="adresse<?= $this->adresse['ID_ADRESSE'] ?? '' ?>">
        <input type='hidden' value='<?= $this->adresse["NUMINSEE_COMMUNE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][NUMINSEE_COMMUNE]' />
        <input type='hidden' value='<?= $this->adresse["LON_ETABLISSEMENTADRESSE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][LON_ETABLISSEMENTADRESSE]' />
        <input type='hidden' value='<?= $this->adresse["LAT_ETABLISSEMENTADRESSE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][LAT_ETABLISSEMENTADRESSE]' />
        <input type='hidden' value='<?= $this->adresse["NUMERO_ADRESSE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][NUMERO_ADRESSE]' />
        <input type='hidden' value='<?= $this->adresse["ID_RUE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][ID_RUE]' />
        <input type='hidden' value='<?= $this->adresse["COMPLEMENT_ADRESSE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][COMPLEMENT_ADRESSE]' />
        <input type='hidden' value='<?= $this->adresse["ADRESSE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][ADRESSE]' />
        <input type='hidden' value='<?= $this->adresse["CODEPOSTAL_COMMUNE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][CODEPOSTAL_COMMUNE]' />
        <input type='hidden' value='<?= $this->adresse["LIBELLE_COMMUNE"] ?? '' ?>' name='ADRESSES[<?= $this->adresse === null ? -1 : $this->adresse['ID_ADRESSE'] ?? '' ?>][LIBELLE_COMMUNE]' />

        <span>
            <?php if ($this->adresse === null): ?>
                Adresse non disponible
                <?php elseif (isset($this->adresse["ADRESSE"]) && $this->adresse["ADRESSE"] !== ""): ?>
                    <?php echo strtolower($this->adresse["ADRESSE"]); ?>
            <?php else: ?>
                <?php echo strtolower(
                    ($this->adresse["NUMERO_ADRESSE"] ?? '') . " " .
                    ($this->adresse["LIBELLE_RUE"] ?? '') . " " .
                    ($this->adresse["COMPLEMENT_ADRESSE"] ?? '') . " " .
                    ($this->adresse["CODEPOSTAL_COMMUNE"] ?? '') . " " .
                    ($this->adresse["LIBELLE_COMMUNE"] ?? '')
                ); ?>
            <?php endif; ?>
        </span>
    </td>
    <td>
        Adresse postale
    </td>
    <td>
        <small>
            <a class="modifierAdresse" data-id="<?= $this->adresse['ID_ADRESSE'] ?? '' ?>" data-toggle="modal" data-backdrop="static" href="#adresse-modal-edit">Modifier</a>
            <a href="#" onclick='$(this).closest("tr").remove(); return false;' class="text-danger">Retirer</a>
        </small>
    </td>
</tr>
