<?php if (empty($this->array)) : ?>
    <p class='text-muted'>Pas d'historique disponible.</p>
<?php else : ?>
    <table class='table table-bordered table-hover'>
        <thead>
            <tr>
                <th style='width: 250px' >Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->array as $item) : ?>
            <tr>
                <td>
                    <?php if (null !== $item["debut"]): ?>
                        Du <?= $item["debut"] ?>
                    <?php else: ?>
                        <?php if ($item['type_dossier'] === 1): ?>
                            Date de commission non renseignée
                        <?php elseif (in_array($item['type_dossier'], [2, 3])): ?>
                            Date de visite non renseignée
                        <?php endif ?>
                    <?php endif ?>
                </td>
                <td>
                    <a href="<?= $item['url'] ?>" target="_blank" title="Ouvrir <?= $item['titre'] ?> (nouvel onglet)"><?= $item["titre"] ?></a>

                    <div>
                        <small class="text-muted"><?= $item['type'] ?></small>

                        <?php if ($item['leve']): ?>
                            <span class="label label-info">
                                Levé<?php if ($item['type'] === 'Dérogation') echo 'e'; ?>
                            </span>
                        <?php endif ?>
                    </div>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
