<div class="modal fade" id="modal-delete-rubrique" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Supprimer une rubrique</h3>
            </div>
            <div class="modal-body">
                Vous êtes sur le point de supprimer la rubrique <strong><span id="name-rubrique"></span></strong>.
                <br />
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<small class="text-muted">Toutes les données associées seront également supprimées.</small>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                <button id="delete-rubrique" type="button" class="btn btn-danger">Supprimer</button>
            </div>
        </div>
    </div>
</div>