<div id="saved-rubriques-prototype" class="hidden col-md-6 col-md-offset-2 saved-rubriques">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Liste des rubriques</h3>
        </div>
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th></th>
                    <th>Nom de la rubrique</th>
                    <th>Afficher la rubrique par défaut</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>