<div id="tocModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4>Rubriques</h4>
    </div>
    <div class="modal-body">
        <?= $this->partial('formulaire/_table_of_content.phtml', [
            'rubriques' => $this->rubriques,
            'idSuffix' => '-modal',
        ]) ?>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
    </div>
</div>
