<link rel="stylesheet" href="/css/formulaire.css" />

<a href="/formulaire">
    <i class="icon-arrow-left"></i>
    Retourner sur la liste des formulaires
</a>

<div class="row-fluid">
    <h3>Informations sur la rubrique</h3>
    <div class="span4 infos-rubrique">
        <form action class="form-inline" method="post">
            <label for="nom_rubrique">Nom de la rubrique</label>
            <input type="text" name="nom_rubrique" id="nom_rubrique" value="<?php echo $this->rubrique['NOM'] ?>" required>
            <label for="afficher_rubrique">Afficher la rubrique par défaut</label>
            <input
                type="hidden"
                name="afficher_rubrique"
                value="0"
            >
            <input
                type="checkbox"
                name="afficher_rubrique"
                value="1"
                <?php echo $this->rubrique['DEFAULT_DISPLAY'] ? 'checked' : '' ?>
            >

            <div class="pull-right">
                <a href='/formulaire' type="button" class="btn">Annuler</a>
                <button type="submit" class="btn btn-success">Sauvegarder la rubrique</button>
            </div>
        </form>
    </div>
</div>

<div class="row-fluid">
    <div class="span4">
        <h3>Informations sur le champ</h3>
    </div>
    <div class="span7 offset1">
        <?php if(count($this->champs) > 0): ?>
            <h3>Liste des champs</h3>
        <?php endif ?>
    </div>
</div>

<div id="edit-rubrique" class="row-fluid">
    <div class="span4 infos-champ">
        <form id="field-form" enctype="application/x-www-form-urlencoded" method="post" class="form-inline" action>
            <?php echo $this->fieldForm->nom_champ ?>
            <?php echo $this->fieldForm->type_champ ?>

            <div id="div-valeurs-liste">
                <h5>Définition des valeurs de la liste</h5>
                <div class="row-fluid">
                    <a href='#' id='add-list-value'>Ajouter une valeur</a>
                </div>
                <div class="row-fluid">
                    <div id="valeurs-liste" class="span10">
                    </div>
                </div>
            </div>

            <?php echo $this->fieldForm->save ?>
        </form>
    </div>

    <div id="saved-fields" class="span7 offset1">
        <?php if(count($this->champs) > 0): ?>
            <table class="table table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Nom du champ</th>
                        <th>Type du champ</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->champs as $champ): ?>
                        <tr>
                            <td><?php echo $champ['NOM'] ?></td>
                            <td>
                                <?php echo $champ['TYPE'] ?>
                                <?php if($champ['TYPE'] === 'Liste'): ?>
                                    <ul>
                                        <?php foreach($champ['VALEURS'] as $valeur): ?>
                                            <li><?php echo $valeur['VALEUR'] ?></li>
                                        <?php endforeach ?>
                                    </ul>
                                <?php endif ?>
                            </td>
                            <td id="actions">
                                <a href="/formulaire/edit-champ/rubrique/<?php echo $this->rubrique['ID_RUBRIQUE'] ?>/champ/<?php echo $champ['ID_CHAMP'] ?>">Modifier</a>
                                <!-- Faire un appel AJAX sur le supprimer pour ne pas avoir à recharger la page -->
                                <a href="/formulaire/delete-champ/rubrique/<?php echo $this->rubrique['ID_RUBRIQUE'] ?>/champ/<?php echo $champ['ID_CHAMP'] ?>">Supprimer</a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        <?php endif ?>
    </div>
</div>