<?php foreach ($this->rubriques as $rubrique): ?>
    <div id='afficher_rubrique-<?= $rubrique['ID_RUBRIQUE'] ?>' class="<?= boolval($rubrique['DISPLAY']) === false ? 'hide' : '' ?>">
        <h4 class='h4_subtitle'><?= $rubrique['NOM'] ?></h4>
        <?php if (empty($rubrique['CHAMPS'])): ?>
            <?= 
                $this->partial('formulaire/partials/partial-information-manquante.phtml', [
                        'message' => 'Aucun champ renseigné. Contactez un administrateur Prevarisc.'
                ]);
            ?>
        <?php else : ?>
            <?php foreach ($rubrique['CHAMPS'] as $champ): ?>
                <div class='control-group'>
                    <label for='champ-<?= htmlspecialchars($champ["ID_CHAMP"]) ?>' class='control-label'>
                        <strong><?= htmlspecialchars($champ['NOM']) ?></strong>
                    </label>
                    <div class='controls'>
                        <?= $this->partial('formulaire/inputChamp.phtml', [
                                'champ' => $champ,
                                'champsvaleurliste' => $this->champsvaleurliste,
                                'listeChampFils' => $this->listeChampFils,
                                'canWrite' => isset($this->canWrite) ? $this->canWrite : true
                            ]); 
                        ?>
                    </div>
                </div>
            <?php endforeach ?>
        <?php endif ?>
    </div>
<?php endforeach ?>