<?php
    $arrayKeys = array_keys($this->formulaires);
    $lastKey = end($arrayKeys);
?>
<?php foreach($this->formulaires as $key => $formulaire) : ?>
    <div id="<?= $formulaire['NOM_INTERNE'] ?>" class="row objet">
        <div class="span12">
            <h2>
                <?= $formulaire['NOM'] ?>
            </h2>

            <div class="row titles">
                <div class="span4">
                    <h3>Informations sur la rubrique</h3>
                </div>

                <?php if(count($formulaire['RUBRIQUES']) > 0): ?>
                    <div class="span6 offset2">
                        <h3>Liste des rubriques</h3>
                    </div>
                <?php endif ?>
            </div>

            <div class="row">
                <div id="<?= $formulaire['NOM_INTERNE'] ?>" class="span4 infos-rubrique">
                    <form action class="form-inline" method="post">
                        <div>
                            <?= $this->form->nom_rubrique->setAttrib('id', sprintf('%s-nom_rubrique', $formulaire['NOM_INTERNE'])) ?>
                        </div>
                        <div>
                            <?= $this->form->afficher_rubrique->setAttrib('id', sprintf('%s-afficher_rubrique', $formulaire['NOM_INTERNE'])) ?>
                        </div>

                        <?= $this->form->save ?>
                    </form>
                </div>

                <div class="span6 offset2 saved-rubriques">
                    <?php if(count($formulaire['RUBRIQUES']) > 0): ?>
                        <table class="table table-bordered table-condensed">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Nom de la rubrique</th>
                                    <th>Afficher la rubrique par défaut</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="capsule-rubrique-<?= $formulaire['ID_CAPSULERUBRIQUE']?>" class="grp">
                                <?php foreach($formulaire['RUBRIQUES'] as $rubrique): ?>
                                    <tr id=<?=$rubrique['ID_RUBRIQUE']?>>
                                        <td class='tdMove'><span class="glyphicon glyphicon-move" aria-hidden="true"></span></td>
                                        <td><?= $rubrique['NOM'] ?></td>
                                        <td id='default-display'>
                                            <?php if($rubrique['DISPLAY']): ?>
                                                <div class="text-center">
                                                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                </div>
                                            <?php endif ?>
                                        </td>
                                        <td id='actions'>
                                            <div class='text-center'>
                                                <a href="<?= $this->url(['controller' => 'formulaire', 'action' => 'edit-rubrique', 'rubrique' => $rubrique['ID_RUBRIQUE']], null, true) ?>">
                                                    <span title='Modifier' class='glyphicon glyphicon-pencil' aria-hidden='true'></span>
                                                </a>
                                                <button data-id="<?= $rubrique['ID_RUBRIQUE'] ?>" data-nom="<?= $rubrique['NOM'] ?>" class="btn btn-link delete-rubrique">
                                                    <i title='Supprimer' class='glyphicon glyphicon-trash' aria-hidden='true'></i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                            </tbody>
                        </table>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>

    <?php if($key !== $lastKey): ?>
        <hr>
    <?php endif;
endforeach ?>
