<?php switch ($this->champ['ID_TYPECHAMP']) {
    // Texte
    case 1: ?>
        <input
            type='text'
            name='champ-<?= $this->champ["ID_CHAMP"] ?>'
            value='<?= isset($this->champ["VALEUR"]) ? htmlspecialchars($this->champ["VALEUR"], ENT_QUOTES) :'' ?>'
        >
    <?php break;
    // Texte long
    case 2: ?>
        <textarea name='champ-<?= $this->champ["ID_CHAMP"] ?>'><?= htmlspecialchars($this->champ["VALEUR"]) ?></textarea>
    <?php break;
    // Liste
    case 3: ?>
        <select name='champ-<?= $this->champ["ID_CHAMP"] ?>'>
            <option selected value>Sélectionnez un élément</option>
            <?php foreach($this->champsvaleurliste[$this->champ['ID_CHAMP']] as $champvaleurliste): ?>
                <option
                    value="<?= htmlspecialchars($champvaleurliste['VALEUR'], ENT_QUOTES) ?>"
                    <?= $champvaleurliste['VALEUR'] === $this->champ['VALEUR'] ? 'selected' : '' ?>
                >
                    <?= $champvaleurliste['VALEUR'] ?>
                </option>
            <?php endforeach ?>
        </select>
    <?php break;
    // Nombre
    case 4: ?>
        <input type='number' name='champ-<?= $this->champ["ID_CHAMP"] ?>' min='0' value='<?= htmlspecialchars($this->champ["VALEUR"]) ?>'>
    <?php break;
    // Case à cocher
    case 5: ?>
        <input
            type="hidden"
            name='champ-<?= $this->champ["ID_CHAMP"] ?>'
            value="0"
        >
        <input
            type="checkbox"
            name='champ-<?= $this->champ["ID_CHAMP"] ?>'
            value="1"
            <?= htmlspecialchars($this->champ['VALEUR'] != null ? 'checked' : '' )?>
        >
    <?php break;   

    case 6:?>
        <div class="tableInput">
            <?php foreach ($this->listeChampFils as $champsFils): ?>
                <div class="colTableInput">
                    <th><?= $champsFils['NOM'] ?></th>
                    <?= $this->partial('formulaire/inputChamp.phtml', [
                        'champ' => $champsFils,
                        'champsvaleurliste' => $this->champsvaleurliste,
                        'listeChampFils' => $this->listeChampFils,
                        'isChampFils' => true
                        ]); 
                    ?>
                </div>
            <?php endforeach;?>
        </div>
    <?php break;
    default:
        break;
} ?>