<!-- Titre -->
<h3 class='page-header'>Liste des évolutions</h3>
<form action="/liste-des-evolutions/edit" method='post'>
    <ul>
        <?php foreach ($this->datas as $key => $data):
            $check = $data['value'] ? 'checked' : null; ?>
            <li>
                <input type="checkbox" name="<?= $key ?>" <?= $check ?>><?= $data['label'] ?>
            </li>
        <?php endforeach ?>
    </ul>
    <input type='submit' value="activer"/>
</form>
