<div class='action-buttons pull-right'>
    <?php if (!$this->hasData): ?>
        <button type="button" class="btn btn-info recupEffectifsDegagementsDossier">
            Reprendre les données d'une étude précédente
        </button>
    <?php endif ?>
    <a class='btn btn-default' href="<?= $this->url(array('action' => 'effectifs-degagements-dossier-edit')) ?>">Modifier les effectifs et dégagements</a>
</div>

<div id='descriptif-personnalise'>
    <h3>Effectifs et Dégagements</h3>

    <h4 class='h4_subtitle'>Rubriques</h4>
    <div class="descriptif-personnalise_rubriques-infos">
        <?= $this->partialLoop('formulaire/partials/partial-rubrique-display.phtml', $this->rubriques) ?>
    </div>

    <div id='affichage-informations' class='form-horizontal'>
        <?= $this->partial('formulaire/partials/partial-form-custom.phtml', [
            'rubriques' => $this->rubriques,
            'champsvaleurliste' => $this->champsvaleurliste,
            'canWrite' => false
        ]); ?>
    </div>
</div>

<script type='text/javascript'>
    $(document).ready(function() {
	    var dialogRecupEffectifsDegagements = $('<div style="display:none;"></div>').appendTo('body');

        dialogRecupEffectifsDegagements.dialog({
            title: "Reprise des données d'un dossier précédent",
            modal: true,
            autoOpen: false,
            width: 1200,
            height: 'auto',
            buttons: [
                {
                    text: 'Reprendre les effectifs et dégagements',
                    class: 'btn btn-success',
                    click: function() {
                        if ($('input[type=radio][name=dossierSelect]:checked').length == 1) {
                            $.ajax({
                                type: "POST",
                                url: "/dossier/recupeffectifsdegagements",
                                data: $("#selectionDossier").serialize(),
                                before: function(){
                                    dialogRecupEffectifsDegagements.html("Veuillez patienter pendant la reprise des effectifs et dégagements <img src='/images/load.gif' />");
                                },
                                success: function(msg){ 
                                    window.location='/dossier/effectifs-degagements-dossier/id/'+$("#idDossier").val();
                                }
                            });
                        } else {
                            return false;
                        }

                        return false;
                    }
                },
                {
                    text: 'Annuler',
                    class: 'btn btn-default',
                    click: function() {
                        $(this).html("");
                        $(this).dialog("close");
                    }
                }
            ],
        });

        $(".recupEffectifsDegagementsDossier").live('click',function(){
            $.ajax({
                type: "POST",
                url: "/dossier/formrecupeffectifsdegagements",
                data: "&idDossier="+$("#idDossier").val(),
                success: function(msg){
                    dialogRecupEffectifsDegagements.html(msg);
                    dialogRecupEffectifsDegagements.dialog("open");
                }
            });

            return false;
        });
    })
</script>
