SET NAMES 'utf8';

CREATE TABLE `rubrique` (
    `ID_RUBRIQUE` bigint(20) NOT NULL AUTO_INCREMENT,
    `NOM` varchar(255) NOT NULL,
    `DEFAULT_DISPLAY` TINYINT(1) DEFAULT 0,
    `ID_CAPSULERUBRIQUE` bigint(20) NOT NULL,
    PRIMARY KEY (`ID_RUBRIQUE`),
    CONSTRAINT `fk_rubrique_capsuleRubrique` FOREIGN KEY (`ID_CAPSULERUBRIQUE`) REFERENCES `capsulerubrique` (`ID_CAPSULERUBRIQUE`) ON DELETE CASCADE ON UPDATE CASCADE
);