<!doctype html>
<html lang="fr" >
    <head>
        <style>body { padding-top: 80px; }</style>
        <?php echo $this->render("includes/header.phtml"); ?>
    </head>

    <body>
        <?php echo $this->render("includes/nav-main.phtml"); ?>

        <div class='container-fluid'>
            <div class='row-fluid'>
                <div class='span10' style="margin-top: 70px;">
                  <?php echo $this->placeholder('page_header') ?>
                  <?php echo $this->render("includes/notifications.phtml"); ?>

                  <div class="dashboard">
                    <?php echo $this->placeholder('before_content') ?>
                    <?php echo $this->layout()->content; ?>
                  </div>

                  <?php echo $this->placeholder('after_content') ?>
                </div>
            </div>
            <button id="go-top" type="button" class="btn hide" onclick="scrollToTop()">
                <i class="icon-arrow-up"></i>
            </button>
            <div class='row-fluid'>
                <div class="span12">
                    <?php echo $this->render("includes/footer.phtml"); ?>
                </div>
            </div>
        </div>

        <script>
          $(document).ready(function() {
              $(".sidebar").css('height', $(document).height() + 'px');
          });
        </script>
    </body>
</html>
