<!doctype html>
<html lang="fr" >
    <head>
        <style>body { padding-top: 80px; }</style>
        <?php echo $this->render("includes/header.phtml"); ?>
    </head>

    <body>
        <?php echo $this->render("includes/nav-main.phtml"); ?>

        <div class='container-fluid'>
            <div class='row'>
                <div class='col-md-2 sidebar mainsidebar' style="margin-top: 20px; padding-top: 40px;">
                    <br>
                    <?php echo $this->avatar(Zend_Auth::getInstance()->getIdentity()['ID_UTILISATEUR'], 'medium', array('style' => "float: left; width: 50px; border: 1px solid #dfdfdf; border-radius: 50%; margin-right: 15px;")) ?>

                    <p style="line-height:15px">
                      <strong>Bonjour <?php echo Zend_Auth::getInstance()->getIdentity()['infos']['PRENOM_UTILISATEURINFORMATIONS'] ?></strong><br>
                      <a class="deconnexion" href="<?php echo $this->url(array('controller' => 'session', 'action' => 'logout'), null, true) ?>">Déconnexion</a><br><br>
                      <small class="label label-success" style="font-size: .8em">En ligne</small>
                    </p>

                    <hr class='clearfix' style="border: none;" />
                    <?php echo $this->placeholder('lateral_navigation'); ?>
                </div>

                <div class='col-md-10' style="margin-top: 70px;">
                  <?php echo $this->placeholder('page_header') ?>
                  <?php echo $this->render("includes/notifications.phtml"); ?>

                  <div class="dashboard">
                    <?php echo $this->placeholder('before_content') ?>
                    <?php echo $this->layout()->content; ?>
                  </div>

                  <?php echo $this->placeholder('after_content') ?>
                </div>
            </div>
            <button id="go-top" type="button" class="btn btn-default hide" onclick="scrollToTop()">
                <i class="icon-arrow-up"></i>
            </button>
            <div class='row'>
                <div class="col-md-12">
                    <?php echo $this->render("includes/footer.phtml"); ?>
                </div>
            </div>
        </div>

        <script>
          $(document).ready(function() {
              $(".sidebar").css('height', $(document).height() + 'px');
          });
        </script>
    </body>
</html>
