<?php if($this->action != "add" && $this->do != "new" ) : ?>
<?php $this->placeholder('lateral_navigation')->captureStart(); // Capture du 'lateral_navigation' ?>
<input type='hidden' name='ID_CREATEUR' id='ID_CREATEUR' value='<?php echo $this->idUser; ?>' />
<ul class="nav nav-tabs nav-stacked menu_dashboard" >
    <li class="<?php echo ( $this->action == "index" ) ? "active" : "read" ?>">
        <a
            href='<?php echo $this->url(array("controller" => "dossier", "id" => $this->idDossier), false, true) ?>'><em class="icon-info-sign icon-black"></em> Informations générales</a>
    </li>

	<?php
            if($this->idTypeDossier == 1 && $this->natureDossier != 3 && $this->natureDossier != 9) {
                echo "<li class='".(( $this->action == "descriptif") ? "active" : "read" )."'>
                        <a "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"descriptif", "id" => $this->idDossier), false, true)."'><i class=\"icon-book icon-black\"></i> Descriptif ".(( $this->natureDossier == 1 || $this->natureDossier == 2 ) ? " des travaux" : "")."</a>
                    </li>";
            }

            if ($this->idTypeDossier == 1 || $this->idTypeDossier == 2 || $this->idTypeDossier == 3 ) {
                echo "<li class='".( ( $this->action == "textes-applicables" ) ? "active" : "read" )."'>
                        <a "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"textes-applicables", "id" => $this->idDossier), false, true)."'><i class=\"icon-align-center icon-black\"></i> Textes applicables</a>
                    </li>";
            }

            if ($this->idTypeDossier != 5) {
                echo "<li class='".( ( $this->action == "docconsulte" ) ? "active" : "read" )."'>
                        <a  "
                            . "href='".$this->url(array("controller" => "dossier", "action"=>"docconsulte", "id" => $this->idDossier), false, true)."'><i class=\"icon-file icon-black\"></i> Documents consultés</a>
                    </li>";
            }

            if($this->natureDossier != 3 && $this->natureDossier != 40 && $this->natureDossier != 41 && $this->natureDossier != 42 && $this->natureDossier != 44 && $this->natureDossier != 31 && $this->natureDossier != 32 && $this->idTypeDossier != 5) {
                echo "<li class='".( ( $this->action == "prescription" ) ? "active" : "read" )."'>
                        <a  "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"prescription", "id" => $this->idDossier), false, true)."'><i class=\"icon-flag icon-black\"></i> Prescriptions</a>
                    </li>";
            }
	?>

        <li class='<?php echo ( $this->action == "liees" ) ? "active" : "read" ?>'>
            <a
                href='<?php echo $this->url(array("controller" => "dossier", "action"=>"liees", "id" => $this->idDossier), false, true) ?>'><em class="icon-folder-open icon-black"></em> Établissements et dossiers liés</a>
        </li>

	<?php
            if($this->natureDossier != 40 && $this->natureDossier != 41 && $this->natureDossier != 42 && $this->natureDossier != 44) {
                echo "<li class='".( ( $this->action == "contact" ) ? "active" : "read" )."'>
                        <a  "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"contact", "id" => $this->idDossier), false, true)."'><i class=\"icon-user icon-black\"></i> Contacts</a>
                    </li>";
            }
	?>

        <li class='<?php echo ( $this->action == "piece-jointe" ) ? "active" : "read" ?>'>
            <a
               href='<?php echo $this->url(array("controller" => "dossier", "action"=>"piece-jointe", "id" => $this->idDossier), false, true) ?>'><em class="icon-share icon-black"></em> Pièces jointes</a>
        </li>
        <li class="nav-header">Actions</li>
        <?php
                $verrou = true;
                if ($this->verrou == 1  || (isset($action) && $action == 'new')) {
                        $label = "Déverrouiller";
                        $idLink = "DEVERROU";
                } else {
                        $label = "Verrouiller";
                        $idLink = "VERROU";
                        $verrou = false;
                }
        ?>
        <li>
            <a class="sep" id="<?php echo $idLink; ?>" style='cursor:pointer;'><em class="icon-lock icon-black"></em> <?php echo $label; ?></a>
        </li>
        <?php
            echo "
                <li class='".( ( $this->action == "rapport" ) ? "active" : "read" )."'>
                    <a  "
                    . "href='".$this->url(array("controller" => "dossier", "action"=>"rapport", "id" => $this->idDossier), false, true)."'><i class=\"icon-refresh icon-black\"></i> Rapport</a>
                </li>
            ";
        ?>
        <?php if (!$verrou && ($this->idDateCommissionAffect != null)) : ?>
        <li>
            <a class="sep" href='/calendrier-des-commissions/gestionodj/dateCommId/<?php echo $this->idDateCommissionAffect; ?>'><em class='icon-calendar icon-black'></em> Afficher ordre du jour</a>
        </li>
        <?php endif; ?>
        <?php if(!$verrou && $this->is_allowed_delete_dossier) : ?>
        <li>
            <?php if(null !== $this->infosDossier->DATESUPPRESSION_DOSSIER) : ?>
                <a id="retablissementDossier" href=<?= "/dossier/retablir-dossier/idDossier/". $this->idDossier ?>>
                    <em class="icon-ok icon-black"></em>
                    Rétablir le dossier
                </a>
            <?php else :?>
                <a id="suppressionDossier" href="#">
                    <em class="icon-remove icon-black"></em>
                    Supprimer le dossier
                </a>
            <?php endif; ?>
        </li>
        <?php endif; ?>
    </ul>
<?php $this->placeholder('lateral_navigation')->captureEnd();
endif; ?>

<?php $this->placeholder('page_header')->captureStart();  // Capture du 'before_content' ?>

<?php if($this->action == "add" || $this->do == "new" ) :?>
    <h2 class='page-header'>Création d'un nouveau dossier</h2>
        <h3 class='page-header'>
            <div style='margin:10px;' id='infosEtablissement'>
                <?= $this->enteteEtab['ID_ETABLISSEMENT'] ?>
                <?php if($this->enteteEtab) : ?>
                    Etablissement(s) concerné(s) : &nbsp;
                    <a
                        href= <?= '/etablissement/descriptif/id/'.$this->enteteEtab['ID_ETABLISSEMENT']?>
                        data-target='#modal-desc'
                        data-toggle='modal'
                        id='descEtab'
                        title='Afficher le descriptif'>
                        <i class='icon-list-alt icon-black'></i>
                    </a>
                    <a href=<?= '/etablissement/dossiers/id/'. $this->enteteEtab['ID_ETABLISSEMENT']?>
                        title='Se rendre à la liste des dossiers' >
                        <i class='icon-folder-open icon-black'></i>
                    </a>;

                    <a href=<?= '/etablissement/index/id/'.$this->enteteEtab['ID_ETABLISSEMENT'] ?> class='etab'>

                        <?= $this->enteteEtab['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>

                        <?php if($this->enteteEtab['adresses']) : ?>
                            &nbsp; <?= "(". $this->enteteEtab['adresses'][0]['LIBELLE_COMMUNE'].")" ?>
                        <?php endif; ?>

                        <?php if(isset($this->enteteEtab['etablissementInfos']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'])) :?>
                            [<?= $this->enteteEtab['etablissementInfos']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>]
                        <?php endif; ?>
                    </a>

                    <?php if(isset($this->enteteEtab['etablissementInfos']['general']['ID_DOSSIER_DONNANT_AVIS']) && null !== ($this->enteteEtab['etablissementInfos']['general']['ID_DOSSIER_DONNANT_AVIS'])) :?>
                        <?php if($this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] == "Favorable") :?>
                            <span class='avis F'><?= $this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] ?></span>&nbsp;
                        <?php elseif($this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] == "Défavorable") :?>
                            <span class='avis D'><?= $this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] ?></span>&nbsp;
                        <?php elseif($this->enteteEtab['etablissementInfos']['infosEtab']['presence_avis_differe']) :?>
                            <span class='label label-info'>Avis différé</span>&nbsp;
                        <?php else :?>
                            <span class='avis'>Avis indisponible</span>&nbsp;
                        <?php endif; ?>
                        <?php else:?>
                            <span class='avis'>Avis indisponible</span>&nbsp;
                    <?php endif; ?>

                    <?php $this->nbPrev = sizeof($this->enteteEtab['etablissementInfos']['preventionnistes']) ?>
                    <?php if(sizeof($this->enteteEtab['etablissementInfos']['preventionnistes']) > 0) : ?>
                        <span style='font-size:10px'>(
                            <?php foreach($this->enteteEtab['etablissementInfos']['preventionnistes'] as $prev ): ?>
                                <?= $prev['NOM_UTILISATEURINFORMATIONS']." ".$prev['PRENOM_UTILISATEURINFORMATIONS'] ?>
                                <?php if($this->nbPrev > 1) :?>
                                    <?php $this->nbPrev-- ?>
                                    ,
                                <?php endif; ?>
                            <?php endforeach; ?>
                        )</span>
                    <?php endif ?>
                    <span style='font-size:10px'>#<?= $this->enteteEtab['etablissementInfos']['general']['NUMEROID_ETABLISSEMENT'] ?></span>
                <?php endif; ?>
            </div>
        </h3>

<?php else :?>
    <h2 class='page-header'>
        <span style='color: #333333'><?= $this->libelleType ?></span>
        <?php if(null !== $this->infosDossier->DATESUPPRESSION_DOSSIER) :?>
            <span class='label label-important'>
                DOSSIER SUPPRIME
            </span>
        <?php endif; ?>
        <small><br/><?= nl2br($this->objetDossier) ?></small>
        <?php if(null !== $this->id_platau) :?>
            <p style='font-size: medium;' class='label label-info'>
                <strong>CONSULTATION PLATAU : <?= $this->id_platau ?></strong>
            </p>
        <?php endif; ?>
        <div style='margin:10px;' id='infosEtabs'>
            <?php if(count($this->enteteEtab)> 0) :?>
                <?php if($this->nbEtab == 1 && $this->enteteEtab[0]["LIBELLE_GENRE"] == "Site") :?>
                    Site concerné :
                    <a href=<?='/etablissement/index/id/'.$this->enteteEtab[0]['ID_ETABLISSEMENT'] ?> class='etab'>
                        <?= $this->enteteEtab[0]['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>
                    </a>
                    <span style='font-size:10px'>#<?=$this->enteteEtab[0]['infosEtab']['general']['NUMEROID_ETABLISSEMENT'] ?></span>
                <?php else:?>
                    Etablissement(s) concerné(s) :
                    <?php foreach($this->enteteEtab as $etab => $value) :?>
                        <?php if(true || $value['ID_ETABLISSEMENTDOSSIER'] !== $idEtabEnCour) :?>
                            <a
                                href=<?= '/etablissement/descriptif/id/'.strval($value['ID_ETABLISSEMENT']) ?>
                                data-target='#modal-desc'
                                data-toggle='modal'
                                id='descEtab'
                                title='Afficher le descriptif'>
                                <i class='icon-list-alt icon-black'></i>
                            </a>
                            &nbsp;
                            <a
                                href='/etablissement/dossiers/id/'.<?=$value['ID_ETABLISSEMENT']?>
                                title='Se rendre à la liste des dossiers' >
                                <i class='icon-folder-open icon-black'></i>
                            </a>
                            &nbsp;
                            <a
                                href=  <?='/etablissement/index/id/'.$value['ID_ETABLISSEMENT'] ?>
                                class='etab'>
                                <?= $value['LIBELLE_ETABLISSEMENTINFORMATIONS']?>
                                <?php $this->nbAdresse = count($value['infosEtab']['adresses']) ?>
                                <?php if($this->nbAdresse != 0):?>
                                    (
                                        <?php foreach($value['infosEtab']['adresses'] as $commune):?>
                                            <?= $commune['LIBELLE_COMMUNE'] ?>
                                            <?php if($this->nbAdresse > 1) :?>
                                                <?php $this->nbAdresse-- ?>
                                            <?php endif ?>
                                        <?php endforeach; ?>
                                    )
                                <?php else :?>
                                 (adresse non renseignée)
                                <?php endif ?>
                                <?php if(isset($value['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'])): ?>
                                    [<?= $value['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>]
                                <?php endif; ?>
                            </a>
                            <?php if($value['infosEtab']['general']['ID_DOSSIER_DONNANT_AVIS'] != null) :?>
                                <?php if($value['avisExploitation']['LIBELLE_AVIS'] == "Favorable"):?>
                                    <span class='avis F'><?= $value['avisExploitation']['LIBELLE_AVIS'] ?></span>&nbsp;
                                <?php elseif($value['avisExploitation']['LIBELLE_AVIS'] == "Défavorable"):?>
                                    <span class='avis D'><?=$value['avisExploitation']['LIBELLE_AVIS']?></span>&nbsp;
                                <?php elseif($value['infosEtab']['presence_avis_differe']):?>
                                    <span class='label label-info'>Avis différé</span>&nbsp;
                                <?php else:?>
                                    <span class='avis'>Avis indisponible</span>&nbsp;
                                <?php endif;?>
                            <?php else : ?>
                                <span class='avis'>Avis indisponible</span>&nbsp;
                            <?php endif; ?>

                            <?php $this->nbPrev = count($value['infosEtab']['preventionnistes']) ?>
                            <?php if($this->nbPrev > 0) :?>
                                <span style='font-size:10px'>
                                (
                                    <?php foreach($value['infosEtab']['preventionnistes'] as $prev) : ?>
                                        <?=
                                            $prev['NOM_UTILISATEURINFORMATIONS']
                                            ." ".
                                            $prev['PRENOM_UTILISATEURINFORMATIONS']
                                        ?>
                                        <?php if($this->nbPrev > 1) :?>
                                            <?php $this->nbPrev-- ?>
                                            ,
                                        <?php endif ?>
                                    <?php endforeach ?>
                                )
                            <?php endif ?>
                            <span style='font-size:10px'>#<?=$value['infosEtab']['general']['NUMEROID_ETABLISSEMENT']?></span>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </h2>
<?php endif; ?>


<div class='grid_16' >

<?php echo "<input type='hidden' name='idDossier' id='idDossier' value='".$this->idDossier."' />"; ?>

<?php $this->placeholder('page_header')->captureEnd(); //$this->placeholder('before_content')->captureEnd() ?>


<?php $this->placeholder('after_content')->captureStart() // Capture du 'after_content' ?>

</div>
    <!-- Modal -->
	<div class="modal hide fade" tabindex="-1" id="modal-desc" >
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">x</button>
					<h3>Descriptif de l'établissement</h3>
				</div>
				<div class="modal-body">
					Chargement des éléments...
				</div>
				<div class="modal-footer">
					<a href="#" class="btn" data-dismiss="modal">Fermer</a>
				</div>
			</div>
		</div>
	</div>
<script>
    $(document).ready(function(){
		$("#VERROU").live('click',function(){
			$.ajax({
					url: "/dossier/verrou",
					data: "idDossier="+$("#idDossier").val()+"&ID_CREATEUR="+$("#ID_CREATEUR").val(),
					type:"POST",
					beforeSend: function(){
						$("#chargement").html("<img src='/images/load.gif' />");
					},
					success: function(affichageResultat){
						window.location= affichageResultat;
					},
					statusCode: {
                        401:function(){
                            alert("Vous n'êtes pas autorisé à effectuer cette action");
                            $("#chargement").html("");
                        },
					},
					error: function(){
                        return false;
					}
			});
			return false;
		});

		$("#DEVERROU").live('click',function(){
			$.ajax({
                url: "/dossier/deverrou",
                data: "idDossier="+$("#idDossier").val(),
                type:"POST",
                beforeSend: function(){
                    $("#chargement").html("<img src='/images/load.gif' />");
                },
                success: function(affichageResultat){
                    window.location= affichageResultat;
                },
                statusCode: {
                    401:function(){
                        alert("Vous n'êtes pas autorisé à effectuer cette action");
                        $("#chargement").html("");
                    },
                },
                error: function(){
                    return false;
                }
			});
			return false;
		});
    });
</script>
<?php $this->placeholder('after_content')->captureEnd() ?>

<?php echo $this->render('dashboard.phtml') // Rendu du layout par défaut avec les placeholders ?>
