<?php if ($this->action != "add" && $this->do != "new") : ?>
    <?php $this->placeholder('lateral_navigation')->captureStart(); // Capture du 'lateral_navigation'?>

    <input type='hidden' name='ID_CREATEUR' id='ID_CREATEUR' value='<?= $this->idUser; ?>' />

    <ul class="nav nav-tabs nav-stacked menu_dashboard" >
        <li class="<?= ($this->action == "index") ? "active" : "" ?>">
            <a href='<?= $this->url(array("controller" => "dossier", "id" => $this->idDossier), false, true) ?>'>
                <i class="icon-info-sign icon-black"></i>
                Informations générales
            </a>
        </li>

        <?php if ($this->idTypeDossier == 1 && $this->natureDossier != 3 && $this->natureDossier != 9): ?>
            <li class='<?= ($this->action == "descriptif") ? "active" : "" ?>'>
                <a href='<?= $this->url(array("controller" => "dossier", "action" => "descriptif", "id" => $this->idDossier), false, true) ?>'>
                    <i class="icon-book icon-black"></i>
                    Descriptif <?php if ($this->natureDossier == 1 || $this->natureDossier == 2) ?> des travaux
                </a>
            </li>
        <?php endif ?>

        <?php if ($this->idTypeDossier == 1 || $this->idTypeDossier == 2 || $this->idTypeDossier == 3): ?>
            <li class='<?= strpos($this->action, "textes-applicables") !== false ? "active" : "" ?>'>
                <a href='<?= $this->url(array("controller" => "dossier", "action" => "textes-applicables", "id" => $this->idDossier), false, true) ?>'>
                    <i class="icon-align-center icon-black"></i>
                    Textes applicables
                </a>
            </li>
        <?php endif ?>

        <?php if ($this->idTypeDossier != 5): ?>
            <li class = <?= $this->action == "docconsulte" ? "active" : "" ?>>
                <a href= <?= $this->url(array("controller" => "dossier", "action" => "docconsulte", "id" => $this->idDossier), false, true) ?>>
                    <i class="icon-file icon-black"></i>
                    Documents consultés
                </a>
            </li>
        <?php endif ?>

        <?php if (($this->idTypeDossier === 2 || $this->idTypeDossier === 3) && $this->isAllowedVerificationsTechniques): ?>
            <li class="<?= strpos($this->action, 'verifications-techniques') !== false ? 'active' : '' ?>">
                <a href= <?= $this->url(array("controller" => "dossier", "action" => "verifications-techniques", "id" => $this->idDossier), false, true) ?>>
                    <i class="icon-file icon-black"></i>
                    Vérifications techniques
                </a>
            </li>
        <?php endif ?>

        <?php if ($this->idTypeDossier === 1 && $this->isAllowedEffectifsDegagements): ?>
            <li class="<?= strpos($this->action, 'effectifs-degagements-dossier') !== false ? 'active' : '' ?>">
                <a class='sep' href='<?= $this->url(array('action' => 'effectifs-degagements-dossier')) ?>' >
                    <i class="icon-th-list icon-black"></i>
                    Effectifs et dégagements
                </a>
            </li>
        <?php endif ?>

        <?php if ($this->idTypeDossier === 1 && $this->isAllowedAvisDerogation): ?>
            <li class="<?= strpos($this->action, 'avis-et-derogations') !== false ? 'active' : '' ?>">
                <a href="<?= $this->url(['controller' => 'dossier', 'action' => 'avis-et-derogations', 'id' => $this->idDossier], false, true) ?>">
                    <i class="icon-file icon-black"></i>
                    Avis et dérogations

                    <?php if($this->hasAvisDerogation): ?>
                        <div class="greenCircle pull-right"></div>
                    <?php endif ?>
                </a>
            </li>
        <?php endif ?>

        <?php if (!in_array($this->natureDossier, [3, 5, 31, 32, 40, 41, 42, 44])): ?>
            <li class="<?= strpos($this->action, 'prescription') !== false ? 'active' : '' ?>">
                <a href='<?= $this->url(array("controller" => "dossier", "action" => "prescription", "id" => $this->idDossier), false, true) ?>'>
                    <i class="icon-flag icon-black"></i>
                    Prescriptions
                </a>
            </li>
        <?php endif ?>

        <li class='<?= ($this->action == "liees") ? "active" : "" ?>'>
            <a href='<?= $this->url(array("controller" => "dossier", "action" => "liees", "id" => $this->idDossier), false, true) ?>'>
                <i class="icon-folder-open icon-black"></i>
                Établissements et dossiers liés
            </a>
        </li>

        <?php if (!in_array($this->natureDossier, [40, 41, 42, 44])): ?>
            <li class='<?= ($this->action == "contact") ? "active" : "" ?>'>
                <a href='<?= $this->url(array("controller" => "dossier", "action" => "contact", "id" => $this->idDossier), false, true) ?>'>
                    <i class="icon-user icon-black"></i>
                    Contacts
                </a>
            </li>
        <?php endif ?>

        <li class='<?= ($this->action == "piece-jointe") ? "active" : "" ?>'>
            <a href='<?= $this->url(array("controller" => "dossier", "action" => "piece-jointe", "id" => $this->idDossier), false, true) ?>'>
                <i class="icon-share icon-black"></i>
                Pièces jointes
            </a>
        </li>

        <li class="nav-header">Actions</li>

        <?php
            $verrou = true;
            if ($this->verrou == 1  || (isset($action) && $action == 'new')) {
                $label = "Déverrouiller";
                $idLink = "DEVERROU";
            } else {
                $label = "Verrouiller";
                $idLink = "VERROU";
                $verrou = false;
            }
        ?>

        <li>
            <a class="sep" id="<?= $idLink; ?>" style='cursor:pointer;'><i class="icon-lock icon-black"></i> <?= $label; ?></a>
        </li>

        <li class='<?= ($this->action == "rapport") ? "active" : "read" ?>'>
            <a href='<?= $this->url(array("controller" => "dossier", "action" => "rapport", "id" => $this->idDossier), false, true) ?>'>
                <i class="icon-refresh icon-black"></i>
                Rapport
            </a>
        </li>

        <?php if (!$verrou && ($this->idDateCommissionAffect != null)) : ?>
            <li>
                <a class="sep" href='/calendrier-des-commissions/gestionodj/dateCommId/<?= $this->idDateCommissionAffect; ?>'>
                    <i class='icon-calendar icon-black'></i> Afficher ordre du jour
                </a>
            </li>
        <?php endif ?>

        <?php if (!$verrou && $this->is_allowed_delete_dossier) : ?>
            <li>
                <?php if ($this->dossierSupprime) : ?>
                    <a id="retablissementDossier" href=<?= "/dossier/retablir-dossier/idDossier/". $this->idDossier ?>>
                        <i class="icon-ok icon-black"></i>
                        Rétablir le dossier
                    </a>
                <?php else :?>
                    <a id="suppressionDossier" href="#">
                        <i class="icon-remove icon-black"></i>
                        Supprimer le dossier
                    </a>
                <?php endif ?>
            </li>
        <?php endif ?>
    </ul>

    <?php $this->placeholder('lateral_navigation')->captureEnd();
endif ?>

<?php $this->placeholder('page_header')->captureStart();  // Capture du 'before_content'?>

<?php if($this->action == "add" || $this->do == "new" ): ?>
    <h2 class='page-header'>Création d'un nouveau dossier</h2>
    <h3 class='page-header'>
        <div style='margin:10px; line-height: 20px;' id='infosEtablissement'>
            <?php if($this->enteteEtab) : ?>
                Etablissement(s) concerné(s) :
                <a
                    href= <?= '/etablissement/descriptif/id/'.$this->enteteEtab['ID_ETABLISSEMENT']?>
                    data-target='#modal-desc'
                    data-toggle='modal'
                    id='descEtab'
                    title='Afficher le descriptif'>
                    <i class='icon-list-alt icon-black'></i>
                </a>
                <a href=<?= '/etablissement/dossiers/id/'. $this->enteteEtab['ID_ETABLISSEMENT']?>
                    title='Se rendre à la liste des dossiers' >
                    <i class='icon-folder-open icon-black'></i>
                </a>

                <a href=<?= '/etablissement/index/id/'.$this->enteteEtab['ID_ETABLISSEMENT'] ?> class='etab'>
                    <?= $this->enteteEtab['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>

                    <?php if($this->enteteEtab['adresses']) : ?>
                        (<?= $this->enteteEtab['adresses'][0]['LIBELLE_COMMUNE'] ?>)
                    <?php endif ?>

                    <?php if(isset($this->enteteEtab['etablissementInfos']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'])): ?>
                        [<?= $this->enteteEtab['etablissementInfos']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>]
                    <?php endif ?>
                </a>

                <?php if(isset($this->enteteEtab['etablissementInfos']['general']['ID_DOSSIER_DONNANT_AVIS']) && null !== ($this->enteteEtab['etablissementInfos']['general']['ID_DOSSIER_DONNANT_AVIS'])): ?>
                    <?php if($this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] == "Favorable"): ?>
                        <span class='avis F'><?= $this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] ?></span>
                    <?php elseif($this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] == "Défavorable"): ?>
                        <span class='avis D'><?= $this->enteteEtab['etablissementInfos']['avisExploitation']['LIBELLE_AVIS'] ?></span>&nbsp;
                    <?php elseif($this->enteteEtab['etablissementInfos']['infosEtab']['presence_avis_differe']): ?>
                        <span class='label label-info'>Avis différé</span>&nbsp;
                    <?php else: ?>
                        <span class='avis'>Avis indisponible</span>&nbsp;
                    <?php endif ?>
                <?php else: ?>
                    <span class='avis'>Avis indisponible</span>&nbsp;
                <?php endif ?>

                <?php $nbPrev = sizeof($this->enteteEtab['etablissementInfos']['preventionnistes']) ?>
                <?php if($nbPrev > 0) : ?>
                    <span style='font-size:10px'>(
                        <?php foreach($this->enteteEtab['etablissementInfos']['preventionnistes'] as $prev ): ?>
                            <?= $prev['NOM_UTILISATEURINFORMATIONS']." ".$prev['PRENOM_UTILISATEURINFORMATIONS'] ?>
                            <?php if($nbPrev > 1): ?>
                                <?php $nbPrev-- ?>
                                ,
                            <?php endif ?>
                        <?php endforeach ?>
                    )</span>
                <?php endif ?>

                <span style='font-size:10px'>#<?= $this->enteteEtab['etablissementInfos']['general']['NUMEROID_ETABLISSEMENT'] ?></span>
            <?php endif ?>
        </div>
    </h3>
<?php else :?>
    <h2 class='page-header'>
        <span style='color: #333333'><?= $this->libelleType ?></span>

        <?php if ($this->dossierSupprime): ?>
            <span class='label label-important'>
                DOSSIER SUPPRIME
            </span>
        <?php endif ?>

        <small><br/><?= nl2br($this->objetDossier) ?></small>

	    <?php if (null !== $this->id_platau): ?>
            <p style='font-size: medium;' class='dossier__identifiant-platau label label-info'>
                <strong>CONSULTATION PLATAU : <?= $this->id_platau ?></strong>
            </p>
        <?php endif ?>

        <div style='margin:10px; line-height: 20px;' id='infosEtabs'>
            <?php
            $nbEtab = count($this->enteteEtab);

            if($nbEtab > 0): ?>
                <?php if($nbEtab == 1 && $this->enteteEtab[0]["LIBELLE_GENRE"] == "Site"): ?>
                    Site concerné :
                    <a href=<?='/etablissement/index/id/'.$this->enteteEtab[0]['ID_ETABLISSEMENT'] ?> class='etab'>
                        <?= $this->enteteEtab[0]['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>
                    </a>
                    <span style='font-size:10px'>#<?=$this->enteteEtab[0]['infosEtab']['general']['NUMEROID_ETABLISSEMENT'] ?></span>
                <?php else:
                    $idEtabEnCour = null;
                ?>
                    Etablissement(s) concerné(s) :
                    <?php foreach($this->enteteEtab as $etab => $value): ?>
                        <?php if($value['ID_ETABLISSEMENTDOSSIER'] !== $idEtabEnCour) :
                            $idEtabEnCour = $value['ID_ETABLISSEMENTDOSSIER'];
                        ?>
                            <a
                                href=<?= '/etablissement/descriptif/id/'.$value['ID_ETABLISSEMENT'] ?>
                                data-target='#modal-desc'
                                data-toggle='modal'
                                id='descEtab'
                                title='Afficher le descriptif'>
                                <i class='icon-list-alt icon-black'></i>
                            </a>
                            <a
                                href=<?= '/etablissement/dossiers/id/'.$value['ID_ETABLISSEMENT'] ?>
                                title='Se rendre à la liste des dossiers' >
                                <i class='icon-folder-open icon-black'></i>
                            </a>
                            <a
                                href=<?='/etablissement/index/id/'.$value['ID_ETABLISSEMENT'] ?>
                                class='etab'
                            >
                                <?= $value['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>
                                <?php
                                    $nbAdresse = count($value['infosEtab']['adresses']);

                                    if($nbAdresse != 0): ?>
                                    (<?php foreach($value['infosEtab']['adresses'] as $commune): ?><?= $commune['LIBELLE_COMMUNE'] ?><?php if($nbAdresse != 1): ?>,<?php $nbAdresse-- ?><?php endif ?><?php endforeach ?>)
                                <?php else: ?>
                                    (adresse non renseignée)
                                <?php endif ?>

                                <?php if(isset($value['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'])): ?>
                                    [<?= $value['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>]
                                <?php endif ?>
                            </a>

                            <?php if($value['infosEtab']['general']['ID_DOSSIER_DONNANT_AVIS'] != null): ?>
                                <?php if($value['avisExploitation']['LIBELLE_AVIS'] == "Favorable"): ?>
                                    <span class='avis F'><?= $value['avisExploitation']['LIBELLE_AVIS'] ?></span>&nbsp;
                                <?php elseif($value['avisExploitation']['LIBELLE_AVIS'] == "Défavorable"): ?>
                                    <span class='avis D'><?=$value['avisExploitation']['LIBELLE_AVIS']?></span>&nbsp;
                                <?php elseif($value['infosEtab']['presence_avis_differe']): ?>
                                    <span class='label label-info'>Avis différé</span>&nbsp;
                                <?php else: ?>
                                    <span class='avis'>Avis indisponible</span>&nbsp;
                                <?php endif ?>
                            <?php else: ?>
                                <span class='avis'>Avis indisponible</span>&nbsp;
                            <?php endif ?>

                            <?php $nbPrev = count($value['infosEtab']['preventionnistes']) ?>

                            <?php if($nbPrev > 0): ?>
                                <span style='font-size:10px'>
                                (
                                    <?php foreach($value['infosEtab']['preventionnistes'] as $prev) : ?>
                                        <?=
                                            $prev['NOM_UTILISATEURINFORMATIONS']
                                            ." ".
                                            $prev['PRENOM_UTILISATEURINFORMATIONS']
                                        ?>
                                        <?php if($nbPrev > 1): ?>
                                            ,
                                        <?php endif;
                                        $nbPrev--;
                                    endforeach ?>
                                )
                            <?php endif ?>
                            <span style='font-size:10px'>#<?=$value['infosEtab']['general']['NUMEROID_ETABLISSEMENT']?></span>
                        <?php endif ?>
                    <?php endforeach ?>
                <?php endif ?>
            <?php endif ?>
        </div>
    </h2>
<?php endif ?>

<div class='grid_16' >
    <?= "<input type='hidden' name='idDossier' id='idDossier' value='".$this->idDossier."' />"; ?>

    <?php $this->placeholder('page_header')->captureEnd(); //$this->placeholder('before_content')->captureEnd()?>
    <?php $this->placeholder('after_content')->captureStart() // Capture du 'after_content'?>
</div>

<!-- Modal -->
<div class="modal hide fade" tabindex="-1" id="modal-desc" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>Descriptif de l'établissement</h3>
            </div>
            <div class="modal-body">
                Chargement des éléments...
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Fermer</a>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
		$("#VERROU").live('click',function(){
			$.ajax({
                url: "/dossier/verrou",
                data: "idDossier="+$("#idDossier").val()+"&ID_CREATEUR="+$("#ID_CREATEUR").val(),
                type:"POST",
                beforeSend: function(){
                    $("#chargement").html("<img src='/images/load.gif' />");
                },
                success: function(affichageResultat){
                    window.location= affichageResultat;
                },
                statusCode: {
                    401:function(){
                        alert("Vous n'êtes pas autorisé à effectuer cette action");
                        $("#chargement").html("");
                    },
                },
                error: function(){
                    return false;
                }
			});

			return false;
		});

		$("#DEVERROU").live('click',function(){
			$.ajax({
                url: "/dossier/deverrou",
                data: "idDossier="+$("#idDossier").val(),
                type:"POST",
                beforeSend: function(){
                    $("#chargement").html("<img src='/images/load.gif' />");
                },
                success: function(affichageResultat){
                    window.location= affichageResultat;
                },
                statusCode: {
                    401:function(){
                        alert("Vous n'êtes pas autorisé à effectuer cette action");
                        $("#chargement").html("");
                    },
                },
                error: function(){
                    return false;
                }
			});

			return false;
		});
    });
</script>

<?php $this->placeholder('after_content')->captureEnd() ?>

<?= $this->render('dashboard.phtml') // Rendu du layout par défaut avec les placeholders?>
