<!doctype html>
<html lang="fr" >
    <head>
        <style>body { padding-top: 80px; }</style>
        <?php echo $this->render("includes/header.phtml"); ?>
    </head>

    <body>
        <?php echo $this->render("includes/nav-main.phtml"); ?>

        <div class='container-fluid' >
             <div class='row-fluid'>
                <div class='span12'>
                    <?php echo $this->render("includes/notifications.phtml"); ?>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>

            <?php echo $this->render("includes/footer.phtml"); ?>
        </div>
    </body>
</html>
