<!DOCTYPE html>

<html lang="fr">
    <head>
        <style>body { padding-top: 80px; }</style>
        <?php echo $this->render("includes/header.phtml"); ?>
    </head>

    <body>
        <?php echo $this->render("includes/nav-main.phtml"); ?>

        <div class='container-fluid' >
            <div id='main-content' class='row page-header'>
                <div class='col-md-12'>
                    <h2>
                      <?php echo $this->avatar(Zend_Auth::getInstance()->getIdentity()['ID_UTILISATEUR'], 'medium', array('style' => "float: left; width: 50px; border: 1px solid #dfdfdf; border-radius: 50%; margin-right: 15px;")) ?>
                      Tableau de bord
                      <small>Profil : <?php echo $this->user['group']['LIBELLE_GROUPE'] ?></small>
                    </h2>
                    <span>
                        Bonjour <?php echo Zend_Auth::getInstance()->getIdentity()['infos']['PRENOM_UTILISATEURINFORMATIONS'] ?>
                        <a class="deconnexion" href="<?php echo $this->url(array('controller' => 'session', 'action' => 'logout'), null, true) ?>">Déconnexion</a>
                    </span>
                    <a id="reinitBlocOrder" class="btn btn-default btn-sm pull-right" href="#">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Ré-initialiser les blocs
                    </a>
                </div>
            </div>

            <div class='row'>
                <div class='col-md-12'>
                    <?php echo $this->render("includes/notifications.phtml"); ?>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>

            <div class="row">
                <?php echo $this->render("includes/footer.phtml"); ?>
            </div>
        </div>
    </body>
</html>
