<?php $this->placeholder('lateral_navigation')->captureStart(); // Capture du 'lateral_navigation' ?>
<ul class="nav nav-tabs nav-stacked menu_dashboard">
    <li class="nav-header">Général</li>

    <li>
        <a href='/admin'><i class="icon-info-sign icon-black"></i> Informations</a>
    </li>

    <li class="nav-header">Gestion des entités</li>

    <li>
        <a href='/admin/elements-supprimes'><i class="icon-ok icon-black"></i> Gestion des éléments supprimés</a>
    </li>

    <li>
        <a href='/admin/utilisateurs'><i class="icon-user icon-black"></i> Gestion des utilisateurs</a>
    </li>

    <li>
        <a href='/admin/communes'><i class="icon-globe icon-black"></i> Gestion des communes</a>
    </li>

    <li>
        <a href='/admin/fusion-des-communes'><i class="icon-random icon-black"></i> Fusion des communes</a>
    </li>

    <li>
        <a href='/admin/couches-cartographiques'><i class="icon-map-marker icon-black"></i> Gestion des couches cartographiques</a>
    </li>

    <li <?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'gestion-des-commissions') echo "class='active'" ?> >
        <a href='/gestion-des-commissions' ><i class="icon-certificate icon-black"></i> Gestion des commissions</a>
    </li>

    <li>
        <a href='/admin/documents'><i class="icon-file icon-black"></i> Gestion des documents</a>
    </li>

    <li <?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'gestion-prescriptions') echo "class='active'" ?> >
        <a href='/gestion-prescriptions' ><i class="icon-flag icon-black"></i> Gestion des prescriptions</a>
    </li>

    <li>
        <a href='/admin/textes-applicables'><i class="icon-align-center icon-black"></i> Gestion des textes applicables</a>
    </li>

    <li class="nav-header">Paramétrage du logiciel</li>

    <li>
        <a href='/admin/tableau-des-periodicites'><i class="icon-th icon-black"></i> Tableau des périodicités</a>
    </li>

    <li <?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'groupement') echo "class='active'" ?> >
        <a href='/groupement' ><i class="icon-tags icon-black"></i> Groupements de communes</a>
    </li>

    <li>
        <a href='/admin/changement'><i class="icon-bell icon-black"></i> Messages des alertes</a>
    </li>

    <li <?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'formulaire') echo "class='active'" ?> >
        <a href='/admin/formulaires' ><i class="icon-tasks icon-black"></i> Formulaires</a>
    </li>
</ul>

<?php $this->placeholder('lateral_navigation')->captureEnd(); ?>
<?php $this->placeholder('before_content')->captureStart() // Capture du 'before_content' ?>

<h2 class='page-header'>Administration</h2>

<div class='row-fluid'>
   <div class='span12' >
        <?php $this->placeholder('before_content')->captureEnd() ?>
        <?php $this->placeholder('after_content')->captureStart() // Capture du 'after_content' ?>
   </div>
</div>

<?php $this->placeholder('after_content')->captureEnd() ?>
<?php echo $this->render('dashboard.phtml') // Rendu du layout par défaut avec les placeholders ?>
