name: Prevarisc Lint

on:
  pull_request:
  push:
    branches:
      - 2.5
      - develop

jobs:
  validate-composer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

  php-cs-fixer:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
    - uses: ramsey/composer-install@v3
      with:
        composer-options: "--prefer-dist"
        working-directory: "tools"

    - name: PHP-CS-Fixer
      run: tools/vendor/bin/php-cs-fixer fix --diff --dry-run

  rector:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
    - uses: ramsey/composer-install@v3
      with:
        composer-options: "--prefer-dist"
        working-directory: "tools"

    - name: Rector
      run: tools/vendor/bin/rector process --dry-run
  
  phpstan:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
    - uses: ramsey/composer-install@v3
      with:
        composer-options: "--prefer-dist --ignore-platform-req=php+"
    - uses: ramsey/composer-install@v3
      with:
        composer-options: "--prefer-dist"
        working-directory: "tools"

    - name: PHPStan
      run: tools/vendor/bin/phpstan analyse

  phpunit:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'
        coverage: none
    - uses: ramsey/composer-install@v3
      with:
        composer-options: "--prefer-dist"

    - name: PHPUnit
      run: composer test

  var-dump-check:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'
        coverage: none

    - name: Normal VarDump Check
      uses: umutphp/php-var-dump-check-action@v2
      with:
        checktype: 'none'
        exclude: '$GITHUB_WORKSPACE/vendor'
        extensions: 'php,phtml'

    - name: Zend VarDump Check
      uses: umutphp/php-var-dump-check-action@v2
      with:
        checktype: 'zend'
        exclude: '$GITHUB_WORKSPACE/vendor'
        extensions: 'php,phtml'

  magical-number-check:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
    - uses: ramsey/composer-install@v3
      with:
        composer-options: "--prefer-dist"
        working-directory: "tools"

    - name: Magical Number Check
      run: tools/vendor/bin/phpmnd $GITHUB_WORKSPACE/application --extensions=-switch_case --ignore-numbers=-1
