name: PHP Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: PHP-CS-Fixer
      run: ./vendor/bin/php-cs-fixer fix --diff --dry-run

    - name: Normal VarDump Check
      uses: umutphp/php-var-dump-check-action@v2
      with:
        checktype: 'none'
        exclude: '$GITHUB_WORKSPACE/vendor'
        extensions: 'php,phtml'

    - name: Zend VarDump Check
      uses: umutphp/php-var-dump-check-action@v2
      with:
        checktype: 'zend'
        exclude: '$GITHUB_WORKSPACE/vendor'
        extensions: 'php,phtml'

    - name: PHP Magic Number Check
      uses: umutphp/php-magic-number-check-action@v2
