name: Prevarisc PR Check

on: pull_request

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checks non-draft PR has label
        uses: ryanvade/enforce-active-pr-labeled-action@v1